### ISSUE TITLE
皮皮虾去广告水印

### ISSUE THREAD

**Issue by bywangpp** [NobyDa/Script#100]
升级完脚本，surge第一次进皮皮虾必爆内存

**Comment by NobyDa** [comment]
可以尝试把最大响应尺寸改为64kb

**Comment by bywangpp** [comment]
好的 谢谢大佬

**Comment by Liquor030** [comment]
> 升级完脚本，surge第一次进皮皮虾必爆内存

如果只需要去广告功能请在[URL Rewrite]中添加 

```
# Remove Super's Ad (By Liquor030)
app_name=super&([\S]*)aid=\d+ app_name=super_pro&$1aid=1412 header
``` 

可大幅改善使用体验，强烈建议添加并禁用该脚本，在需要的时候开启脚本去水印！！

**Comment by Littlecowherd** [comment]
> > 升级完脚本，surge第一次进皮皮虾必爆内存
> 
> 如果只需要去广告功能请在[URL Rewrite]中添加
> 
> ```
> # Remove Super's Ad (By Liquor030)
> app_name=super&([\S]*)aid=\d+ app_name=super_pro&$1aid=1412 header
> ```
> 
> 可大幅改善使用体验，强烈建议添加并禁用该脚本，在需要的时候开启脚本去水印！！

有点没太理解这个去广告的规则，不知大佬可否解释一下（我想写下 Qx对应的规则）
跪谢
@Liquor030
