### ISSUE TITLE
请教大神，这些店铺的京豆，可否添加个脚本领取，谢谢

### ISSUE THREAD

**Issue by liamhui** [NobyDa/Script#104]
请教大神，这些店铺的京豆，可否添加个脚本领取，谢谢
https://www.smzdm.com/p/20312659/#hfeeds

**Comment by liamhui** [comment]
https://www.smzdm.com/p/20312659/

这个地址

**Comment by NobyDa** [comment]
店铺京豆一般是临时的, 故不处理这种接口

**Comment by liamhui** [comment]
哦哦，明白。


NobyDa <notifications@github.com> 于2020年4月12日周日 下午6:04写道：
