### ISSUE TITLE
Serious issue in Download.list

### ISSUE THREAD

**Issue by Blankwonder** [NobyDa/Script#108]
We received a report from our user that he has some lagging issues. After some digging, we found it's a problem caused by rules in 
https://raw.githubusercontent.com/NobyDa/Script/master/Surge/Download.list

The URL-REGEX rules in it may take more than 5 seconds to evaluate if the URL of the request is complicated.

**Comment by NobyDa** [comment]
Already understood, this Ruleset has now been deleted.

**Comment by Blankwonder** [comment]
Please do not delete the ruleset directly. The users who already used it now always fail to update and continue to use the flawed version.
Just place an empty file in the original path.

**Comment by NobyDa** [comment]
Already edited, and the rules that may cause problems have now been deleted. you can test it. 
The reason may be caused by excessive use of .+
