### ISSUE TITLE
咸鱼图片被reject

### ISSUE THREAD

**Issue by CostinYuan** [NobyDa/Script#11]
![C4576367-A571-49EB-B1CE-5E78386E2F60](https://user-images.githubusercontent.com/31549570/67314511-5899ed80-f537-11e9-8c14-a27303a39a09.png)
![C9CB3B58-9DE5-43EE-A2A6-B7E1D0DCD9A2](https://user-images.githubusercontent.com/31549570/67314561-723b3500-f537-11e9-974a-01824ee7ce0e.png)

**Comment by CostinYuan** [comment]
amdc.m.taobao这个分流会把咸鱼和阿里云都reject

**Comment by CostinYuan** [comment]
是在adrules.list里的

**Comment by NobyDa** [comment]
尝试更新订阅
