### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by viewfirst** [NobyDa/Script#112]
使用的surge,无法配置成功，在完整复制脚本之后，意图开启MITM，但是提示规则必须以final结尾，不解其意。特来请教。

**Comment by NobyDa** [comment]
1. 该项目无完整"Surge配置文件", 所有脚本配置都应添加至您的配置中[Script]字段下, 以及添加主机名至[MITM]的hostmame字段下. 
2. 之所以"必须以final结尾", 是因为配置文件必须添加final规则.

如不理解以上说明, 那可能脚本等高级功能不适合您.
