### ISSUE TITLE
surge B站评论无法显示

### ISSUE THREAD

**Issue by NightAsker** [NobyDa/Script#117]
使用环境：
1. Surge Pro
2. 去广告使用AdRule.list以及Ad rewrite rules module
3. bilibili脚本
出现现象：
1. 关闭后台 重新打开app可以正常显示评论
2. 过几分钟后评论即无法显示

**Comment by NobyDa** [comment]
经测试, 使用bilibili去广告js + AdRule.list + Ad rewrit rules module 没有复现出这个问题.

建议挨个禁用, 排除一下是哪个规则或模块造成的.

**Comment by vhvg** [comment]
> 使用环境：
> 
> 1. Surge Pro
> 2. 去广告使用AdRule.list以及Ad rewrite rules module
> 3. bilibili脚本
>    出现现象：
> 4. 关闭后台 重新打开app可以正常显示评论
> 5. 过几分钟后评论即无法显示

出现了同样的问题，暂时还没排查出是什么规则/模块导致的

**Comment by NightAsker** [comment]
我这边解决了，将dataflow.biliapi.com, data.bilibili.com直连即可。

**Comment by Bruce-panruosong** [comment]
把data.bilibili.com从小黑屋放出来就行了，dataflow.biliapi.com可以继续关着
