### ISSUE TITLE
termius pro失效了吗?

### ISSUE THREAD

**Issue by OpenWaygate** [NobyDa/Script#118]
我用的是QX [毒奶规则](https://github.com/limbopro/Profiles/tree/master/limbopro/Gift/Without/unzip), 里面引用了这里的重写规则, 我发现打开VSCO VIP还在, 但打开termius本地会员没了, 前段时间我看的还有的, 是失效了吗?

**Comment by NobyDa** [comment]
> 我用的是QX [毒奶规则](https://github.com/limbopro/Profiles/tree/master/limbopro/Gift/Without/unzip), 里面引用了这里的重写规则, 我发现打开VSCO VIP还在, 但打开termius本地会员没了, 前段时间我看的还有的, 是失效了吗?


Termius最新版本使用了证书锁定(SSL Pinning) 故MITM失效, 已经无解.

**Comment by githubdulong** [comment]
毒奶的东西不要用



**Comment by OpenWaygate** [comment]
> 毒奶的东西不要用 
> […](#)
> 在 2020年5月17日，18:38，NobyDa ***@***.***> 写道： ﻿ 我用的是QX 毒奶规则, 里面引用了这里的重写规则, 我发现打开VSCO VIP还在, 但打开termius本地会员没了, 前段时间我看的还有的, 是失效了吗? Termius最新版本使用了证书锁定(SSL Pinning) 故MITM失效, 已经无解. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

为什么啊😂? 这里面有什么讲究吗? 或者有哪个规则推荐的?
