### ISSUE TITLE
开启ad rewrite rule 后，中信动卡空间无法打开

### ISSUE THREAD

**Issue by z4jst** [NobyDa/Script#121]
相关域名
ecitic，任何一条规则都会导致app无法正常运行。

**Comment by NobyDa** [comment]
试了一下, app可以正常联网(未注册), 具体哪里无法正常运行?

**Comment by z4jst** [comment]
🤦‍♂️今天可以了。
前天发 issue 的时候，加上 rewrite 后，打开app会提示，服务器维护，整个app无法运行。
在之前还会提示开启了vpn，请关闭后在运行。

现在有点怀疑检测 vpn的 是它们远程控制开关的。
