### ISSUE TITLE
是否考虑拆分京东签到脚本？

### ISSUE THREAD

**Issue by likecreep** [NobyDa/Script#122]
目前京东签到的请求的接口较多（谢谢作者的用心），但是同时导致js文件也比较大容易爆内存。比如刚刚自动执行时爆掉了，然后我手动执行又爆了一次，第三次才执行成功。
我在想是否可以拆分成两个脚本文件，队列执行，这样可以增加定时任务的稳定性。
谢谢。

**Comment by NobyDa** [comment]
这种情况似乎只出现在iOS11或12系统, 如出现请自行调整为串行签到 (var stop = 1)

**Comment by likecreep** [comment]
> 这种情况似乎只出现在iOS11或12系统, 如出现请自行调整为串行签到 (var stop = 1)

谢谢，刚刚改为串行签到测试是稳定了。（系统是13.5之前也不是每次都会爆，只是有一定概率，仅供参考）

**Comment by NobyDa** [comment]
哪个app, qx?

**Comment by likecreep** [comment]
> 哪个app, qx?

surge 商店最新版本

**Comment by likecreep** [comment]
改为串行执行后有一个问题。双账户的话，第一次脚本执行只会执行账户一的签到。需要二次执行，并且第二次执行是先执行账户2，再执行账户1的签到。 
（ 改回并行执行又炸了，好像是只有双账户才会炸，奇怪的是手动执行炸的几率很低，往往是cron定时执行的时候炸，不知道该怎么办了🙃）

**Comment by NobyDa** [comment]
1. 脚本内执行逻辑不存在 "先执行账户2" 

2. 根据我们的测试, Surge在执行脚本超过5秒的情况下 (串行耗时太久), 会强行终止"账户2"的通知, 直到手动执行下一次脚本才会弹出"上一次执行"的"账户2"通知, 暂不清楚是否为Surge的Bug, 这可能是由于Surge默认脚本超时为5秒.

3. 请尝试在Surge脚本的UI界面调整您的脚本超时为20秒以上, 如无法解决 ,请反馈Bug给Surge开发者.

**Comment by likecreep** [comment]
> 1. 脚本内执行逻辑不存在 "先执行账户2" 
> 
> 
> 
> 2. 根据我们的测试, Surge在执行脚本超过5秒的情况下 (串行耗时太久), 会强行终止"账户2"的通知, 直到手动执行下一次脚本才会弹出"上一次执行"的"账户2"通知, 暂不清楚是否为Surge的Bug, 这可能是由于Surge默认脚本超时为5秒.
> 
> 
> 
> 3. 请尝试在Surge脚本的UI界面调整您的脚本超时为20秒以上, 如无法解决 ,请反馈Bug给Surge开发者.

辛苦了。测试了下串行通知问题应该是由于surge采取的方式造成的。 我先关闭issue吧。 good night
