### ISSUE TITLE
有一条和 YouTube 去广告的 module 冲突，导致无法跳过广告…

### ISSUE THREAD

**Issue by voicistcolin** [NobyDa/Script#125]
^https?:\/\/.+\.googlevideo\.com\/.+(&oad|ctier) - reject

这一条和很多 YouTube App 去片头广告的 module 冲突了（比如 https://raw.githubusercontent.com/lhie1/Rules/master/Surge/Surge%203/Module/YouTube.sgmodule ），以前是没问题的，但现在好像调整了优先级？如果有上面那条，YouTube 就无法跳过片头广告（不显示广告，但要等 10s）。

**Comment by NobyDa** [comment]
已修改为使用脚本处理.

YouTube 去广告可能会造成以下问题:

网页版无法正常播放
YouTube Premium 用户无法正常播放

所以默认并没有启用，如果仍需启用需添加主机名到MITM列表中：

```
*.googlevideo.com
```
