### ISSUE TITLE
京东金融-双签 TypeError

### ISSUE THREAD

**Issue by OpenWaygate** [NobyDa/Script#126]
<img width="566" alt="E0CA04FEC166712AC274B80AE2D3B10A" src="https://user-images.githubusercontent.com/27287694/83357515-6520d700-a39f-11ea-93af-85ef151162dd.png">

我把651行`cc.resultData.data.businessData.businessCode == "000sq" && `删了之后签到成功了.

https://github.com/NobyDa/Script/blob/2cc7b429056c663cd58e76d0d1bfc702963ecb2a/JD-DailyBonus/JD_DailyBonus.js#L651-L654

**Comment by NobyDa** [comment]
现已尝试修正.
