### ISSUE TITLE
iqiyi.js错误调用done()

### ISSUE THREAD

**Issue by likecreep** [NobyDa/Script#127]
iqiyi脚本的 第55行var done = $nobyda.done(); 错误的在脚本还未结束时调用了$done()，可能导致脚本提前终止的bug。
不方便用电脑所以没有提pr，希望作者修改一下，谢谢。

**Comment by NobyDa** [comment]
如果是Surge: 提前终止是因为脚本默认5秒超时, 请自行在脚本配置界面更改超时, 如20秒

如果是QX: 这段代码并不会执行
