### ISSUE TITLE
建议将 RewriteRules.sgmodule 中的 YoutubeAds 脚本去除

### ISSUE THREAD

**Issue by luzhaohui** [NobyDa/Script#129]
如题，去除，或用原作者的地址。
一般会将 YoutubeAds 单独设置 Module，两个地址不一致，会导致 Surge 下载两份 YoutubeAds.js 脚本。

**Comment by NobyDa** [comment]
> 如题，去除，或用原作者的地址。
> 一般会将 YoutubeAds 单独设置 Module，两个地址不一致，会导致 Surge 下载两份 YoutubeAds.js 脚本。

两份脚本理论只会生效一份, 并无实际影响.
