### ISSUE TITLE
大佬，京东签到如何正确获取双cookie，我试了下会出现覆盖，只存在一个cookie

### ISSUE THREAD

**Issue by kai2ou** [NobyDa/Script#130]
`*********************
【 配置双京东账号签到说明 】 : 
*********************

正确配置QX、Surge、Loon后, 并使用此脚本获取"账号1"Cookie成功后, 请勿点击退出账号(可能会导致Cookie失效), 需清除浏览器资料或更换浏览器登录"账号2"获取即可.
`

`请问这个如何正确操作？我用safari登入账号1，alook登入账号2，获取的cookie会覆盖，只能获得一个cookie`

**Comment by NobyDa** [comment]
不可能会覆盖, 除非你两个账号的"用户名"完全一样.

**Comment by kai2ou** [comment]
@NobyDa 
用户名是京东默认的

**Comment by NobyDa** [comment]
原因不明, 脚本没法取就手动抓cookie填入脚本吧.

**Comment by kai2ou** [comment]
@NobyDa 

我采用原来单独获取cookie的脚本，实现了获取2个cookie的目的。

**Comment by MisterGlasses** [comment]
> 原因不明, 脚本没法取就手动抓cookie填入脚本吧.

请问安卓端如何抓取cookie?

**Comment by NobyDa** [comment]
> > 原因不明, 脚本没法取就手动抓cookie填入脚本吧.
> 
> 请问安卓端如何抓取cookie?

不太了解安卓的抓包app, 其实都是跟脚本里ios手抓cookie一个方法, 搜索关键字即可.

**Comment by MisterGlasses** [comment]
> > > 原因不明, 脚本没法取就手动抓cookie填入脚本吧.
> > 
> > 
> > 请问安卓端如何抓取cookie?
> 
> 不太了解安卓的抓包app, 其实都是跟脚本里ios手抓cookie一个方法, 搜索关键字即可.

关键词是什么 CookieQY?

**Comment by MisterGlasses** [comment]
> > > 原因不明, 脚本没法取就手动抓cookie填入脚本吧.
> > 
> > 
> > 请问安卓端如何抓取cookie?
> 
> 不太了解安卓的抓包app, 其实都是跟脚本里ios手抓cookie一个方法, 搜索关键字即可.

我想抓爱奇艺的cookie

**Comment by NobyDa** [comment]
> > > > 原因不明, 脚本没法取就手动抓cookie填入脚本吧.
> > > 
> > > 
> > > 请问安卓端如何抓取cookie?
> > 
> > 不太了解安卓的抓包app, 其实都是跟脚本里ios手抓cookie一个方法, 搜索关键字即可.
> 
> 我想抓爱奇艺的cookie

url里的authcookie=后面的字母数字混合的就是, 到&结束

**Comment by Ang-Hong** [comment]
> 原因不明, 脚本没法取就手动抓cookie填入脚本吧.

大哥，请教一下，如果手动填CK？我有cookie，但不知道如何手动填。不知道要填在脚本的哪个地方。

**Comment by NobyDa** [comment]
> > 原因不明, 脚本没法取就手动抓cookie填入脚本吧.
> 
> 大哥，请教一下，如果手动填CK？我有cookie，但不知道如何手动填。不知道要填在脚本的哪个地方。

看脚本内注释
