### ISSUE TITLE
京东个护清洁签到失败

### ISSUE THREAD

**Issue by AnnoRoland** [NobyDa/Script#133]
https://3.cn/12lYFw-7
家庭清洁馆
https://3.cn/12-kINZ2
个护馆

**Comment by NobyDa** [comment]
由于身心的不可抗力, 该项目暂缓.

**Comment by tianya908** [comment]
还是感谢分享

**Comment by AnnoRoland** [comment]
> 还是感谢分享

作者还是抽空更新了一次，更新接口了

**Comment by AnnoRoland** [comment]
个护清洁接口已经更新，珠宝亦修复，感谢
