### ISSUE TITLE
Zhihu cannot work using AdblockRegex.list

### ISSUE THREAD

**Issue by qinyuhang** [NobyDa/Script#136]
Rule with Problem
`^https?:\/\/(api|www)\.zhihu\.com\/((terms\/privacy\/confirm|app_config|banner|commercial_api\/(launch|real_time))|(fringe|zst|drama|adx|commercial|real_time|ad-style-service|banners|market/popover|mqtt|.*(launch|featured-comment-ad|guide|recommendations|community-ad)|search/(top|tab|preset)|ab))`

Link blocked
`https://www.zhihu.com/appview/p/56435917?no_image=false&article_fixed_bottom=1&X-SUGER=SURGVj1GMzRCMDUzRi03M0JBLTQxMDctQjNFNC0wN0RGRjM2OEEyNEE7SURGQT1DMEEwMzE2Qi1DQzQ4LTQ2ODAtQTk0NC0zQ0ZDNDlCRTAwMjU7VURJRD1BREFqU0puYnhROUxCYXNEb1NWQVhtS2tqSFI1Z1E3dW45MD0%3D&X-AD=canvas_version%3Av%3D4.1%3Bsetting%3Acad%3D0&follow_guide=1&is_enable_double_click_voteup=1&use_hybrid_toolbar=1&ab_signature=CiRBREFqU0puYnhROUxCYXNEb1NWQVhtS2tqSFI1Z1E3dW45MD0SIDkxNDZhOTMwNDUzOWEzOTgyMjA1YmJkOTE1YTBhY2ZlGhAIAhIGNi40NS4xGgQyMzM0`

if delete `follow_guide=1` it will not match the Regex, I suggest break the complex Regex to more simple Regex

**Comment by NobyDa** [comment]
Now this rule already separated.

**Comment by qinyuhang** [comment]
> Now this rule already separated.

It's working again, good job!
