### ISSUE TITLE
百度贴吧的cookie获取失败

### ISSUE THREAD

**Issue by Au3C2** [NobyDa/Script#137]
最近百度贴吧的cookie获取失败，其他应用都能正常获取，请问作者知道是怎么回事吗？

**Comment by NobyDa** [comment]
正则匹配URL临时改成:
^https?:\/\/.*\/c\/s\/login$

**Comment by Au3C2** [comment]
谢谢您！

**Comment by Au3C2** [comment]
换上之后马上试了，好像还是不行

**Comment by NobyDa** [comment]
如未解决, 可尝试改为https?:\/\/(c\.tieba\.baidu\.com|180\.97\.\d+\.\d+)\/c\/s\/login
实测没问题

**Comment by samrtman** [comment]
怎么禁用cookie呢？开始我以为是在调试模块的构造请求里面将百度贴吧禁用后来发现这样就没法签到了，可是查看脚本又不可以更改，谢谢你，大佬🧍‍♂️
