### ISSUE TITLE
如何在浏览器里面运行`JD_DailyBonus.js`

### ISSUE THREAD

**Issue by duchenpaul** [NobyDa/Script#141]
我是js小白, 请问如何在pc chrome 上运行你的JD_DailyBonus.js

**Comment by NobyDa** [comment]
可以借助在线node.js平台: https://repl.it/languages/nodejs
该平台可能需要科学的网络环境, 直接拖入或粘贴脚本执行即可.

**Comment by duchenpaul** [comment]
可以的谢谢
