### ISSUE TITLE
bilibili漫画请求签到接口失败

### ISSUE THREAD

**Issue by OCD0711** [NobyDa/Script#143]
bilibili漫画请求签到接口失败

**Comment by NobyDa** [comment]
更换网络环境

**Comment by OCD0711** [comment]
> 更换网络环境

Loon和surge会出现这个情况 更换网络也是...其他脚本没问题

**Comment by NobyDa** [comment]
通知第二行是否有错误原因

**Comment by OCD0711** [comment]
Empty response data

**Comment by NobyDa** [comment]
全局direct或proxy试试

**Comment by OCD0711** [comment]
> 全局direct或proxy试试

全局代理或者全局直连也一样

**Comment by NobyDa** [comment]
1. Surge添加MITM = manga.bilibili.com
2. 打开抓取流量, 运行脚本
3. 最近请求找到对应的签到请求, 截图总览的备注与响应.

**Comment by OCD0711** [comment]
> 1. Surge添加MITM = manga.bilibili.com
> 2. 打开抓取流量, 运行脚本
> 3. 最近请求找到对应的签到请求, 截图总览的备注与响应.

loon可以抓取么?...现在没用surge

**Comment by NobyDa** [comment]
Loon TF版目前无法使用该脚本, 主要是Surge不应出现这种情况.

**Comment by OCD0711** [comment]
已经解决
