### ISSUE TITLE
JD签到是不是会导致商品关注和店铺收藏...

### ISSUE THREAD

**Issue by androidcn** [NobyDa/Script#149]
JD签到是不是会导致商品关注和店铺收藏...

以前不会

**Comment by NobyDa** [comment]
不存在关注商品或店铺的行为, 可能是其他项目的京东类脚本导致的.

**Comment by ztxtop** [comment]
种豆得豆的脚本有，看下你是否有用这个脚本

**Comment by androidcn** [comment]
> 不存在关注商品或店铺的行为, 可能是其他项目的京东类脚本导致的.
抱歉误会了

@ztxtop 谢谢提醒，原来是它！

**Comment by 710850609** [comment]
哪里有 “种豆得豆的脚本” 的脚本呢 ？能分享下吗？

**Comment by NobyDa** [comment]
自京东签到[1.37](https://raw.githubusercontent.com/NobyDa/Script/master/JD-DailyBonus/JD_DailyBonus.js)版本开始, 签到过程可能会自动关注某些店铺, 请各位知悉. 如介意, 可使用[1.36](https://raw.githubusercontent.com/NobyDa/Script/0593df308102b5833115ad1ed3dfd49e547b3955/JD-DailyBonus/JD_DailyBonus.js)及以下版本.
