### ISSUE TITLE
JD天天加速js中无法使用

### ISSUE THREAD

**Issue by tiantianwahaha** [NobyDa/Script#154]
你好，首先很感谢你写的一键脚本。
我有一点疑问，就是JD天天加速模块用node.js可以正确运行。
但是放在chrome中纯js运行会返回这个{"code":"1","echo":"cross-origin request from '' is not allowed"}
我想请教下，这个意思是不是说浏览器跨域，是服务器端的设置原因，不是用js能解决的？

**Comment by NobyDa** [comment]
首先你得去理解什么是跨域, 这脚本不是用在浏览器上的.
浏览器在非京东页面开调试去请求京东天天加速的API, 不报跨域报啥...

**Comment by tiantianwahaha** [comment]
> 首先你得去理解什么是跨域, 这脚本不是用在浏览器上的.
> 浏览器在非京东页面开调试去请求京东天天加速的API, 不报跨域报啥...

谢谢回复，我刚大致了解了一下跨域。但是其他的很多模块是可以运行成功的，是不是表示那些的京东服务并没有不允许跨域操作。只有少数的几个会失败。

**Comment by NobyDa** [comment]
浏览器内调试ajax发送请求时会直接忽略掉request header中的Referer字段造成跨域, 其他接口可能没有严格规定Referer.

**Comment by tiantianwahaha** [comment]
明白了，谢谢~
