### ISSUE TITLE
大佬，我还知道一个获取京豆的地方：VX小程序“京东代属”，每天签到8，连签7天至少100京豆

### ISSUE THREAD

**Issue by PoetryU** [NobyDa/Script#160]
大佬，我还知道一个获取京豆的地方：VX小程序“京东代属”，每天签到8，连签7天至少100京豆

这个似乎只有拥有学生认证的才可以用，请问大佬写一下这个脚本吗?

**Comment by NobyDa** [comment]
不考虑有限制的接口
