### ISSUE TITLE
爱奇艺签到存在异常

### ISSUE THREAD

**Issue by MisterGlasses** [NobyDa/Script#161]
![20CB1812-BAE7-4597-8DC0-BADD4022D66A](https://user-images.githubusercontent.com/27768847/88358806-00806800-cda3-11ea-84db-6d584668db91.png)
在我的设备 上，现在已经无法获取cookie，打开爱奇艺后不再有弹窗。
此外，脚本执行时可以签到，但到期时间获取失败，抽奖机始终显示已用完。

**Comment by MisterGlasses** [comment]
![389F6AAA-C5FB-4A7E-8CDB-C11A5D5CCFD2](https://user-images.githubusercontent.com/27768847/88445311-56611880-ce54-11ea-83c3-80aa8a50d2d6.jpeg)

**Comment by MisterGlasses** [comment]
{"code":3,"errorReason":"中奖接口异常VipLotteryResponse(super=AbsAccessorResponse(code=Q00702, msg=抽奖机会用完), data=VipLotteryResponse.LotteryData(giftId=null, giftName=null, daysurpluschance=null, gifttype=null))","isTarget":0,"kv":{"code":"Q00702","msg":"您的抽奖次数已经用完，明日再来吧 "}}

**Comment by NobyDa** [comment]
重取cookie, 再更新脚本试试看.
