### ISSUE TITLE
京东签到存在问题

### ISSUE THREAD

**Issue by askiter** [NobyDa/Script#162]
中从26号的版本之后，签到的时候就看不到执行结果了，手工执行的话，只能看到
Result:
Null
但是jd签到的大部分任务都是正常完成了

其他的签到都是能正常得到消息的。

请问是这部分做了什么调整了么

**Comment by NobyDa** [comment]
没有调整, 因surge商店版限制了签到返回的响应大小 (超过则强行终止脚本), TF版无该问题, 
临时解决办法: 尝试在boxjs禁用珠宝签到 (或脚本内注释掉, 118行开始), 不行的话, 菜场, 美食, 清洁, 个护, 二手, 女装, 超市, 宠物, 图书, 美妆 挨个禁用, 看看问题出在哪个接口.

**Comment by askiter** [comment]
我刚才在BoxJS中挨个禁用测试了一下，同时禁用珠宝签到和京东二手这两个项目之后，脚本工作就正常了。
非常感谢哈

PS：我也是刚刚接触到BoxJS，对这里设置可以影响到脚本执行感觉还是很神奇的，请问哪里可以找到BoxJS的介绍资料，我google都搜不到，谢谢

**Comment by NobyDa** [comment]
可以关注下开发者的TG频道:
https://t.me/chavyscripts
