### ISSUE TITLE
京东签到通知模块TypeError

### ISSUE THREAD

**Issue by MisterGlasses** [NobyDa/Script#163]
task设置为7:01:30运行，实际在7:03:25才运行（爱奇艺也是，但运行成功了）
![C3A1FE41-E731-4931-9F62-CAD56177A262](https://user-images.githubusercontent.com/27768847/88866176-728dfc80-d23c-11ea-8bec-0dcfccb2e9a0.png)

2020/07/30 07:03:25:885  <console>    [QTXTaskManager] Fire task<爱奇艺> https://raw.githubusercontent.com/NobyDa/Script/master/iQIYI-DailyBonus/iQIYI.js.
2020/07/30 07:03:25:904  <console>    [QTXTaskManager] Fire task<京东> https://raw.githubusercontent.com/NobyDa/Script/master/JD-DailyBonus/JD_DailyBonus.js.

运行结果如图
![91702E24-05BB-427D-8DFD-9C527A439E37](https://user-images.githubusercontent.com/27768847/88866189-7de12800-d23c-11ea-9c1e-74153b1352db.png)

**Comment by NobyDa** [comment]
1. 执行时间问题请咨询app开发者.
2. 报错是因为你没更新脚本.

**Comment by czmecho** [comment]
@MisterGlasses 请问联通套餐查询是哪个链接？

**Comment by MisterGlasses** [comment]
> @MisterGlasses 请问联通套餐查询是哪个链接？

chavyleung大佬的
