### ISSUE TITLE
淘宝的比价复写引起网络崩溃的问题

### ISSUE THREAD

**Issue by CostinYuan** [NobyDa/Script#165]
![image](https://user-images.githubusercontent.com/31549570/89099803-6f556500-d424-11ea-9105-cba37fc80e96.png)
![image](https://user-images.githubusercontent.com/31549570/89099807-73818280-d424-11ea-9ca6-d5f9ade078bf.png)
![Uploading 89099810...]()

**Comment by NobyDa** [comment]
如何触发, 这边测试没问题.

**Comment by CostinYuan** [comment]
https://www.smzdm.com/p/23486902/?send_by=4637009748&from=other
值得买右下的直达链接跳转

**Comment by NobyDa** [comment]
> https://www.smzdm.com/p/23486902/?send_by=4637009748&from=other
> 值得买右下的直达链接跳转

![image](https://user-images.githubusercontent.com/53217160/89101848-784f3200-d436-11ea-9ec4-019d22775973.png)
正常打开.

**Comment by CostinYuan** [comment]
em..我再康康咋回事

**Comment by CostinYuan** [comment]
奇怪 我把js的rewrite关掉可以进去，然后打开也可以进了...
