### ISSUE TITLE
有两个问题想咨询一下

### ISSUE THREAD

**Issue by tiantianwahaha** [NobyDa/Script#170]
您好，首先很感谢您的开源代码。
目前我在使用过程中有两个小问题想咨询一下。
1. 天天加速模块，console.log的信息有一点问题，count的数量不知道为什么没有累加，提前就是5了。如下面的例子
天天加速-尝试领取第5个道具
天天加速-已成功领取1个道具
天天加速-尝试领取第5个道具
天天加速-已成功领取2个道具
2.我仿照着写了一个种豆得豆自动领取，但是当我获得要浏览的几个店铺的ID信息，然后循环去浏览时，总是报活动火爆的错误，请问您知道这个应该怎么解决吗。
种豆得豆-尝试浏览第0个店铺response:
{"code":"0","errorCode":"PB001","errorMessage":"抱歉，活动太火爆了"}

**Comment by NobyDa** [comment]
天天加速log在昨天的版本中应该修正了.

种豆得豆不清楚, 但已经有大佬写过这脚本了:
https://gitee.com/lxk0301/scripts

**Comment by tiantianwahaha** [comment]
非常感谢~解决了我的所有疑惑😀

NobyDa <notifications@github.com> 于2020年8月4日周二 下午5:01写道：

**Comment by tiantianwahaha** [comment]
3Q
