### ISSUE TITLE
京东金融的签到有问题

### ISSUE THREAD

**Issue by askiter** [NobyDa/Script#171]
京东金融App里面手工签到的时候，是可以看到签到日历里面有对勾的。
但是用脚本签到后，下面的按钮状态是已经签过到的样子，但是日历里面的状态仍然是未签到，也不会计算连续签到日数

麻烦检查一下，谢谢

**Comment by NobyDa** [comment]
钢镚正常到账, 毫无问题.
日历里的连签是瓜分金币的临时活动, 没什么作用.
如介意可以手签后再用脚本签.
