### ISSUE TITLE
百度云倍速失效,求大佬更新脚本

### ISSUE THREAD

**Issue by TroyXZW** [NobyDa/Script#174]
BaiduCloud.js一周前还可以用，现在报错：
Exception {"line":46}, SyntaxError: Unexpected end of script, nzw9314/NobyDa/Surge/JS/BaiduCloud.js

**Comment by NobyDa** [comment]
试一下把这脚本的最后一行删掉

**Comment by TroyXZW** [comment]
大佬打扰了，已经用了刚刚您更新的脚本，不知道为啥还是报一样的错

**Comment by NobyDa** [comment]
> 大佬打扰了，已经用了刚刚您更新的脚本，不知道为啥还是报一样的错

nzw9314还没更新吧, 看你不是挂载我的库

**Comment by TroyXZW** [comment]
是直接挂载你的库呢，而且还是用了刚刚你更新的脚本呢

**Comment by NobyDa** [comment]
> 是直接挂载你的库呢，而且还是用了刚刚你更新的脚本呢

脚本没有任何问题, 如果报Exception {"line":46}就是没有更新脚本, 自行检查
