### ISSUE TITLE
爱奇艺签到问题

### ISSUE THREAD

**Issue by askiter** [NobyDa/Script#179]
你好，

目前发现爱奇艺签到有点问题，签到的日志如下：

Log:
16:42:08.434147 爱奇艺-查询失败: 无到期数据  
16:42:08.824096 爱奇艺-签到成功: 成长值+3，已连签20天  
16:42:09.665298 爱奇艺-抽奖失败: 用户登录信息失效  (1) 
16:42:10.333791 爱奇艺-抽奖失败: 用户登录信息失效  (2) 
16:42:10.981296 爱奇艺-抽奖失败: 用户登录信息失效  (3) 
16:42:10.984188 
签到用时: 3.27 秒

其中有几个失败，麻烦看一下，谢谢

**Comment by NobyDa** [comment]
赠送的会员好像没法抽奖, 重取下Cookie试试.

**Comment by askiter** [comment]
我打开了抓取cookie的模块，不过不会提示cookie获取信息，需要到哪里手工删除么？
我也不知道自己的会员是不是赠送的。。。

**Comment by DoveBoy** [comment]
> 赠送的会员好像没法抽奖, 重取下Cookie试试.

大佬能不能增加爱奇艺nodejs的方式签到？没有苹果设备QX，Surge，Loon都用不了

**Comment by NobyDa** [comment]
> > 赠送的会员好像没法抽奖, 重取下Cookie试试.
> 
> 大佬能不能增加爱奇艺nodejs的方式签到？没有苹果设备QX，Surge，Loon都用不了

兼容nodejs的, 自行抓cookie

**Comment by DoveBoy** [comment]
> > > 赠送的会员好像没法抽奖, 重取下Cookie试试.
> > 
> > 
> > 大佬能不能增加爱奇艺nodejs的方式签到？没有苹果设备QX，Surge，Loon都用不了
> 
> 兼容nodejs的, 自行抓cookie

具体抓取后的cookie怎么设置？试过，运行会报错

**Comment by NobyDa** [comment]
> > > > 赠送的会员好像没法抽奖, 重取下Cookie试试.
> > > 
> > > 
> > > 大佬能不能增加爱奇艺nodejs的方式签到？没有苹果设备QX，Surge，Loon都用不了
> > 
> > 
> > 兼容nodejs的, 自行抓cookie
> 
> 具体抓取后的cookie怎么设置？试过，运行会报错

填到21行单引号内, 试过没问题. 具体报什么错

**Comment by DoveBoy** [comment]
> > > > > 赠送的会员好像没法抽奖, 重取下Cookie试试.
> > > > 
> > > > 
> > > > 大佬能不能增加爱奇艺nodejs的方式签到？没有苹果设备QX，Surge，Loon都用不了
> > > 
> > > 
> > > 兼容nodejs的, 自行抓cookie
> > 
> > 
> > 具体抓取后的cookie怎么设置？试过，运行会报错
> 
> 填到21行单引号内, 试过没问题. 具体报什么错

大佬我不知道在哪个页面抓取cookie，总是提示cookie失效。
是www.iqiyi.com页面还是m.iqiyi.com？
具体抓取哪个request url下的cookie？

**Comment by NobyDa** [comment]
> > > > > > 赠送的会员好像没法抽奖, 重取下Cookie试试.
> > > > > 
> > > > > 
> > > > > 大佬能不能增加爱奇艺nodejs的方式签到？没有苹果设备QX，Surge，Loon都用不了
> > > > 
> > > > 
> > > > 兼容nodejs的, 自行抓cookie
> > > 
> > > 
> > > 具体抓取后的cookie怎么设置？试过，运行会报错
> > 
> > 填到21行单引号内, 试过没问题. 具体报什么错
> 
> 大佬我不知道在哪个页面抓取cookie，总是提示cookie失效。
> 是www.iqiyi.com页面还是m.iqiyi.com？
> 具体抓取哪个request url下的cookie？

看完注释再提问, cookie有可能在url 也有可能在headers

**Comment by DoveBoy** [comment]
> > > > > > > 赠送的会员好像没法抽奖, 重取下Cookie试试.
> > > > > > 
> > > > > > 
> > > > > > 大佬能不能增加爱奇艺nodejs的方式签到？没有苹果设备QX，Surge，Loon都用不了
> > > > > 
> > > > > 
> > > > > 兼容nodejs的, 自行抓cookie
> > > > 
> > > > 
> > > > 具体抓取后的cookie怎么设置？试过，运行会报错
> > > 
> > > 
> > > 填到21行单引号内, 试过没问题. 具体报什么错
> > 
> > 
> > 大佬我不知道在哪个页面抓取cookie，总是提示cookie失效。
> > 是www.iqiyi.com页面还是m.iqiyi.com？
> > 具体抓取哪个request url下的cookie？
> 
> 看完注释再提问, cookie有可能在url 也有可能在headers

安卓手机上没有抓包软件（国区买不了），只能通过Chrome浏览器抓包

**Comment by DoveBoy** [comment]
> > > > > > > 赠送的会员好像没法抽奖, 重取下Cookie试试.
> > > > > > 
> > > > > > 
> > > > > > 大佬能不能增加爱奇艺nodejs的方式签到？没有苹果设备QX，Surge，Loon都用不了
> > > > > 
> > > > > 
> > > > > 兼容nodejs的, 自行抓cookie
> > > > 
> > > > 
> > > > 具体抓取后的cookie怎么设置？试过，运行会报错
> > > 
> > > 
> > > 填到21行单引号内, 试过没问题. 具体报什么错
> > 
> > 
> > 大佬我不知道在哪个页面抓取cookie，总是提示cookie失效。
> > 是www.iqiyi.com页面还是m.iqiyi.com？
> > 具体抓取哪个request url下的cookie？
> 
> 看完注释再提问, cookie有可能在url 也有可能在headers

浏览器下只能抓取P00001=字段，目前跑起来了，大佬能不能出个怎么把脚本设置在腾讯云函数的教程？另外，能否添加一下server酱的接入？考虑一下把腾讯视频签到也加进来吧？

**Comment by cjf935257177** [comment]
为什么surge无法获取cookie，qx可以
