### ISSUE TITLE
百度贴吧不显示头像

### ISSUE THREAD

**Issue by doggonegod** [NobyDa/Script#180]
圈x开启此规则后百度贴吧头像不显示

**Comment by NobyDa** [comment]
哪个规则, 哪个头像? 
试了下, 没什么问题.

**Comment by doggonegod** [comment]
https://github.com/NobyDa/Script/blob/master/QuantumultX/AdRuleTest.list
这个规则，使用后在贴吧里不显示头像
2020年8月15日 +0800 00:18 NobyDa <notifications@github.com>，写道：

**Comment by NobyDa** [comment]
这边测试正常, 自行分析看看是哪条规则导致的.

**Comment by doggonegod** [comment]
好的，谢谢
2020年8月15日 +0800 00:27 NobyDa <notifications@github.com>，写道：
