### ISSUE TITLE
京东签到最近崩溃的几率比较高

### ISSUE THREAD

**Issue by askiter** [NobyDa/Script#182]
大佬你好，

我在BoxJS里面，二手和珠宝始终都是禁用的，
但是最近发现，签到的时候，有一些项目崩溃的几率比较高，我在凌晨和上午的执行的时候都经常碰到
比方说：钟表、宠物、美妆、菜场、美食、清洁、个护，这几个都是特别容易出现崩溃情况，其中宠物可以忽略（基本上是领不到豆的），但是像美食、清洁、个护这几个还是很有必要的。

对于这个情况，请问是否有办法解决，谢谢

**Comment by askiter** [comment]
另外，是否可以实现，执行脚本的时候不会重复执行当天已经成功签到的子任务，这样的话我只需要在定时里面，让这个脚本多次执行就行，也不用担心因为反复请求被jd ban掉的风险，

**Comment by NobyDa** [comment]
由于NE内存或APP的限制, 没有特别好的解决办法, 只能等待Surge更新商店版.
暂不考虑子任务的判断 (懒)

**Comment by happysoul** [comment]
只能使用 Safari浏览器么，使用chrome选择手机模拟登录，cookie里面没有 关键字 functionId=signBean ，ubuntu18 执行node结果提示cookie失效，Key已经放入了cookie，开头字符串是 autoOpenApp_downCloseDate_auto

**Comment by NobyDa** [comment]
> 只能使用 Safari浏览器么，使用chrome选择手机模拟登录，cookie里面没有 关键字 functionId=signBean ，ubuntu18 执行node结果提示cookie失效，Key已经放入了cookie，开头字符串是 autoOpenApp_downCloseDate_auto

该关键字是URL里的, 如果出现签到日历后没有该URL, 则可以从其他URL请求头内的Cookie查找关键字: pt_pin=和pt_pin=
如果Cookie包含这俩关键字, 则该Cookie是有效的, (暂未测试其他URL获取的Cookie有效期)

**Comment by happysoul** [comment]
> > 只能使用 Safari浏览器么，使用chrome选择手机模拟登录，cookie里面没有 关键字 functionId=signBean ，ubuntu18 执行node结果提示cookie失效，Key已经放入了cookie，开头字符串是 autoOpenApp_downCloseDate_auto
> 
> 该关键字是URL里的, 如果出现签到日历后没有该URL, 则可以从其他URL请求头内的Cookie查找关键字: pt_pin=和pt_pin=
> 如果Cookie包含这俩关键字, 则该Cookie是有效的, (暂未测试其他URL获取的Cookie有效期)

昨天试的时候浏览器copy(document.cookie)的时候确实没有pt_pin 和 pt_key 。
今天再打开看到cookie里有了。。神奇
已经加入到 crontab 定时任务

**Comment by happysoul** [comment]
补充下 我是手动从浏览器cookie复制的key和pin追加到字符串中
