### ISSUE TITLE
野比大佬，请问一下，贴吧签到会出现一些吧签到不成功这个事什么原因

### ISSUE THREAD

**Issue by ljk719488841** [NobyDa/Script#183]
有时候失败有时候成功，失败的吧每次也不一样

**Comment by NobyDa** [comment]
凌晨签有可能签到人数多造成失败, 换个时间试试.

**Comment by ljk719488841** [comment]
> 凌晨签有可能签到人数多造成失败, 换个时间试试.
好的 我试试

**Comment by ljk719488841** [comment]
最近两个号 一个只有6个吧都成功，另一个号57个吧每次只能成功10来个，其他的都是失败，原因：need vcode

**Comment by NobyDa** [comment]
need vcode 是因为签到太频繁, 临时ban了
得过几分钟再签, 这个修不了.

**Comment by ljk719488841** [comment]
原来是这样，感谢解答。
