### ISSUE TITLE
淘宝比价会导致一些链接打不开 等久了直接网络崩溃。药品类为主

### ISSUE THREAD

**Issue by lycorisxv** [NobyDa/Script#184]
![115DA6A8-1D14-464B-9858-2F703F43F76B](https://user-images.githubusercontent.com/62493587/90854233-00c65000-e3af-11ea-8320-c63bc58447b3.png)

**Comment by NobyDa** [comment]
简单看了下, 是上游脚本导致的问题. 
可以用解析器把该脚本过滤掉: 
rewrite链接末尾加#out=tb_price.js

或者自行修改比价脚本
脚本第120-121行之间加上:
if (!consumerProtection.serviceProtection) $done({})

**Comment by lycorisxv** [comment]
> 简单看了下, 是上游脚本导致的问题. 
> 可以用解析器把该脚本过滤掉: 
> rewrite链接末尾加#out=tb_price.js
> 
> 或者自行修改比价脚本
> 脚本第120-121行之间加上:
> if (!consumerProtection.serviceProtection) $done({})

反馈给原作者了 不过他也一个月没更新过tb的比价了
qx远程订阅改不了脚本的吧

**Comment by NobyDa** [comment]
> > 简单看了下, 是上游脚本导致的问题. 
> > 可以用解析器把该脚本过滤掉: 
> > rewrite链接末尾加#out=tb_price.js
> > 
> > 或者自行修改比价脚本
> > 脚本第120-121行之间加上:
> > if (!consumerProtection.serviceProtection) $done({})
> 
> 反馈给原作者了 不过他也一个月没更新过tb的比价了
> qx远程订阅改不了脚本的吧 

用资源解析器可以禁用相关脚本, 自行尝试下.

**Comment by lycorisxv** [comment]
> > > 简单看了下, 是上游脚本导致的问题. 
> > > 可以用解析器把该脚本过滤掉: 
> > > rewrite链接末尾加#out=tb_price.js
> > > 
> > > 或者自行修改比价脚本
> > > 脚本第120-121行之间加上:
> > > if (!consumerProtection.serviceProtection) $done({})
> > 
> > 反馈给原作者了 不过他也一个月没更新过tb的比价了
> > qx远程订阅改不了脚本的吧 
> 
> 用资源解析器可以禁用相关脚本, 自行尝试下.

过滤了比价脚本自然是没问题的 不过这样就没有比价了 难做取舍😞
