### ISSUE TITLE
哔哩哔哩漫画无法获取Cookie

### ISSUE THREAD

**Issue by vasewa** [NobyDa/Script#185]
请问大佬，哔哩哔哩漫画获取Cookie时，一直提示“Cookie关键值缺失”是什么原因呢？

**Comment by NobyDa** [comment]
正则匹配url改成:
^https:\/\/manga\.bilibili\.com\/.*User

**Comment by vasewa** [comment]
> 正则匹配url改成:
> 
> ```
> ^https:\/\/manga\.bilibili\.com\/.*User
> ```

好的我试试，谢谢野比大佬！

**Comment by NobyDa** [comment]
> > 正则匹配url改成:
> > ```
> > ^https:\/\/manga\.bilibili\.com\/.*User
> > ```
> 
> 好的我试试，谢谢野比大佬！

不行的话再改成
````
^https:\/\/passport\.(bilibili|biligame|bigfun(app)?).c(n|om)\/api\/login\/sso

mitm = passport.bi*.c*
```

**Comment by vasewa** [comment]
> > > 正则匹配url改成:
> > > ```
> > > ^https:\/\/manga\.bilibili\.com\/.*User
> > > ```
> > 
> > 
> > 好的我试试，谢谢野比大佬！
> 
> 不行的话再改成
> 
> ```
> ^https:\/\/passport\.(bilibili|biligame|bigfun(app)?).c(n|om)\/api\/login\/sso
> 
> mitm = passport.bi*.c*
> ```
> ```

改成下边这个成功了！大佬牛！太牛了！谢谢野比大佬！
