### ISSUE TITLE
订阅了JS和神机的rewrite 去油管广告卡片头

### ISSUE THREAD

**Issue by lifeva** [NobyDa/Script#187]
如题，禁用了JS订阅就可以顺利去广告了，似乎他们有冲突，但看了具体规则，js文件里并没有关于youtube但内容，请大佬关注下，谢谢

**Comment by NobyDa** [comment]
JS订阅内没有youtube相关内容, 理论不存在冲突.
自行搜索Rewrite关键字 googlevideo 检查策略是否为reject-200而非reject.

**Comment by lifeva** [comment]
已确认策略无误，但现象确实是禁用了js订阅就可以顺利去广告了，同样问题在tg群里大家都有反映。确实也是想不通为什么会冲突

**Comment by NobyDa** [comment]
试了一下,卡片头无法复现.

测试神机rewrite为:
```
https://raw.githubusercontent.com/DivineEngine/Profiles/master/Quantumult/Rewrite/YouTube.conf
```
测试JS订阅为:
```
https://raw.githubusercontent.com/NobyDa/Script/master/QuantumultX/Js.conf
```
