### ISSUE TITLE
抖音去广告无水印的js会导致抖音无法刷出视频

### ISSUE THREAD

**Issue by lycorisxv** [NobyDa/Script#189]
禁用js就恢复正常了
![85CBE225-0692-43B0-9230-0C56E790E91A](https://user-images.githubusercontent.com/62493587/91666273-fd109700-eb2d-11ea-8d7b-f5fe5d875839.png)

**Comment by lycorisxv** [comment]
图片是禁用之前的 无法刷出视频

**Comment by NobyDa** [comment]
@lycorisxv 更新订阅和脚本.

**Comment by lycorisxv** [comment]
更新之后还是不行 依旧刷不出来
不过排除了aweme之后就可以了 而且下载的视频也没有水印 这是怎么回事！！！？
(不知道是不是我的错觉 感觉视频好像变模糊了)
![48175167-AE2E-4A8A-948A-C8941FC7250F](https://user-images.githubusercontent.com/62493587/91675192-0e799380-eb6e-11ea-9f8b-1b968ce96abf.png)

**Comment by zsh35** [comment]
> 之后更新还是不行依旧刷不出来
> 不过排除了aweme之后就可以了而且下载的视频也没有水印这是怎么回事！？ （
我也遇到这个问题。

**Comment by lycorisxv** [comment]
> > 之后更新还是不行依旧刷不出来
> 
> > 不过排除了aweme之后就可以了而且下载的视频也没有水印这是怎么回事！？ （
> 
> 我也遇到这个问题。

就很奇怪的哈哈哈 不过现在修复好了
