### ISSUE TITLE
增加Key从文件读取

### ISSUE THREAD

**Issue by westfly** [NobyDa/Script#196]
JD-DailyBonus的key写到了js中了，每次pull不太方便，能否当key为空时，增加从一个文件读取的功能？

**Comment by NobyDa** [comment]
新版已将Cookie持久化, 填写Cookie运行一次后, 后续更新脚本无需再次填写.
待Cookie失效后重新抓取填写即可. 持久化如有问题可反馈

**Comment by westfly** [comment]
是说在脚本中填写了key，待运行成功后，就可以在js中删除key了么。

**Comment by NobyDa** [comment]
> 是说在脚本中填写了key，待运行成功后，就可以在js中删除key了么。

可留可删.
