### ISSUE TITLE
52pojie建议

### ISSUE THREAD

**Issue by DoveBoy** [NobyDa/Script#198]
52pojie签到脚本可否加入nodejs的支持？非常希望能用nodejs，毕竟Qx，Loon，Surge不是每个人都能用的

**Comment by NobyDa** [comment]
现已增加.
由于吾爱的特殊编码问题, node.js环境下可能无法正确判断签到结果, 如有问题可反馈.

**Comment by DoveBoy** [comment]
> 现已增加.
> 由于吾爱的特殊编码问题, node.js环境下可能无法正确判断签到结果, 如有问题可反馈.

已加入云函数测试，目前正常
![image](https://user-images.githubusercontent.com/19201447/92995158-74cdc100-f533-11ea-90ac-b672cf0792c5.png)

**Comment by DoveBoy** [comment]
> 现已增加.
> 由于吾爱的特殊编码问题, node.js环境下可能无法正确判断签到结果, 如有问题可反馈.

大佬，现在nodejs下貌似不能用了，尝试重新抓取cookie，还是失效，可否解决一下？
![image](https://user-images.githubusercontent.com/19201447/93541436-08b2e900-f989-11ea-8c8c-4b382f5d85d8.png)

**Comment by NobyDa** [comment]
> > 现已增加.
> > 由于吾爱的特殊编码问题, node.js环境下可能无法正确判断签到结果, 如有问题可反馈.
> 
> 大佬，现在nodejs下貌似不能用了，尝试重新抓取cookie，还是失效，可否解决一下？

该错误为网络级报错, 看起来是dns查询失败. 
自行检查网络设置.
