### ISSUE TITLE
Node.js 运行 JD 报 Cookie 失效

### ISSUE THREAD

**Issue by kulocora** [NobyDa/Script#200]
但好像其实是签了的...

![图片](https://user-images.githubusercontent.com/12947678/93488891-6f101b00-f939-11ea-8705-b7d7d60f034d.png)

**Comment by NobyDa** [comment]
> 但好像其实是签了的...
> 
> ![图片](https://user-images.githubusercontent.com/12947678/93488891-6f101b00-f939-11ea-8705-b7d7d60f034d.png)
> 

开启响应日志, 看看原始返回内容

**Comment by kulocora** [comment]
> 
> 
> > 但好像其实是签了的...
> > ![图片](https://user-images.githubusercontent.com/12947678/93488891-6f101b00-f939-11ea-8705-b7d7d60f034d.png)
> 
> 开启响应日志, 看看原始返回内容

![图片](https://user-images.githubusercontent.com/12947678/93493021-08d9c700-f93e-11ea-94bd-fb4f1c026857.png)

**Comment by NobyDa** [comment]
正是cookie失效, 没有误判. 重取cookie吧

**Comment by kulocora** [comment]
> 
> 
> 正是cookie失效, 没有误判. 重取cookie吧

重取一万次了，而且只有这三个报失效，别的都正常，难道 Cookie 取法不对吗？我从网页版 jd.com 取的

**Comment by NobyDa** [comment]
检查你的cookie是否有pt_pin=以及pt_pin=的关键字.

**Comment by NobyDa** [comment]
正是cookie失效, 没有误判. 重取cookie吧

> 检查你的cookie是否有pt_key=以及pt_pin=的关键字.

**Comment by NobyDa** [comment]
检查你的cookie是否有pt_key=以及pt_pin=的关键字.

**Comment by kulocora** [comment]
> 
> 
> 检查你的cookie是否有pt_key=以及pt_pin=的关键字.

问题解决，从 m.jd.com 抓就有了，桌面网页版没有这个关键字。
