### ISSUE TITLE
socket hang up

### ISSUE THREAD

**Issue by mingxiaoyu** [NobyDa/Script#204]
京东多合一签到脚本

更新时间: 2020.9.25 0:40 v1.61

‼️京东魔方-查询发生错误
‼️名称: Error
‼️描述: Error: socket hang up

‼️京东商城-国际发生错误
‼️名称: Error
‼️描述: Error: socket hang up

‼️京东转盘-查询发生错误
‼️名称: Error
‼️描述: Error: socket hang up

‼️京东商城-京豆发生错误
‼️名称: Error
‼️描述: Error: socket hang up

‼️京东现金-红包发生错误
‼️名称: Error
‼️描述: Error: socket hang up

‼️京东商城-闪购发生错误
‼️名称: Error
‼️描述: Error: socket hang up

**Comment by NobyDa** [comment]
网络问题, 超时被挂断了

**Comment by mingxiaoyu** [comment]
黑号了？？？没道理我。那时候，我都在看视频
