### ISSUE TITLE
请问有没有可能适配下github action？

### ISSUE THREAD

**Issue by MisterGlasses** [NobyDa/Script#205]
老哥请问有没有可能适配下github action？

**Comment by NobyDa** [comment]
如果指京东签到, 可通过其他作者的项目联动使用github action, 例如:
https://github.com/sazs34/MyActions
https://github.com/lxk0301/scripts

其他签到暂不提供支持, 该项目主要针对移动端用户.

**Comment by MisterGlasses** [comment]
> 如果指京东签到, 可通过其他作者的项目联动使用github action, 例如:
> https://github.com/sazs34/MyActions
> https://github.com/lxk0301/scripts
> 
> 其他签到暂不提供支持, 该项目主要针对移动端用户.

京东的一直在用 爱奇艺 吾爱等脚本有机会适配一下吗

**Comment by BlueskyClouds** [comment]
爱奇艺我有一个 你可以看看https://github.com/BlueskyClouds/iQIYI-DailyBonus

**Comment by MisterGlasses** [comment]
> 爱奇艺我有一个 你可以看看https://github.com/BlueskyClouds/iQIYI-DailyBonus

多谢 我看下

**Comment by jiayiwang5** [comment]
期待适配github action那一天，安卓用户除了这个基本没别的方法稳定运行了。苹果那些软件 安卓一个没有。
