### ISSUE TITLE
Rewrite_lhie1.conf的^https?:\/\/api\.zhihu\.com\/(launch|ad-style-service|app_config|real_time|ab\/api) url reject-img规则

### ISSUE THREAD

**Issue by hazxy** [NobyDa/Script#207]
qx目录下的Rewrite_lhie1.conf里的这条规则
^https?:\/\/api\.zhihu\.com\/(launch|ad-style-service|app_config|real_time|ab\/api) url reject-img
在知乎的现在版本会刷新不了，以及我的这个tab页也木有数据

知乎版本6.59.0,清空了缓存
所用工具为Loon(不知是不是Loon不兼容)

**Comment by Tartarus2014** [comment]
> qx目录下的Rewrite_lhie1.conf里的这条规则
> ^https?://api.zhihu.com/(launch|ad-style-service|app_config|real_time|ab/api) url reject-img
> 在知乎的现在版本会刷新不了，以及我的这个tab页也木有数据
> 
> 知乎版本6.59.0,清空了缓存
> 所用工具为Loon(不知是不是Loon不兼容)

https://github.com/Tartarus2014/For-own-use/tree/master/Loon  用我这个整理过的吧

**Comment by NobyDa** [comment]
> qx目录下的Rewrite_lhie1.conf里的这条规则
> ^https?:\/\/api\.zhihu\.com\/(launch|ad-style-service|app_config|real_time|ab\/api) url reject-img
> 在知乎的现在版本会刷新不了，以及我的这个tab页也木有数据
> 
> 知乎版本6.59.0,清空了缓存
> 所用工具为Loon(不知是不是Loon不兼容)

推测可能是脚本的相互冲突, 经过测试QX和Surge并没有该问题.

**Comment by hazxy** [comment]
> > qx目录下的Rewrite_lhie1.conf里的这条规则
> > ^https?://api.zhihu.com/(launch|ad-style-service|app_config|real_time|ab/api) url reject-img
> > 在知乎的现在版本会刷新不了，以及我的这个tab页也木有数据
> > 知乎版本6.59.0,清空了缓存
> > 所用工具为Loon(不知是不是Loon不兼容)
> 
> 推测可能是脚本的相互冲突, 经过测试QX和Surge并没有该问题.

好的，很有可能是有冲突，谢谢

**Comment by hazxy** [comment]
> > qx目录下的Rewrite_lhie1.conf里的这条规则
> > ^https?://api.zhihu.com/(launch|ad-style-service|app_config|real_time|ab/api) url reject-img
> > 在知乎的现在版本会刷新不了，以及我的这个tab页也木有数据
> > 知乎版本6.59.0,清空了缓存
> > 所用工具为Loon(不知是不是Loon不兼容)
> 
> https://github.com/Tartarus2014/For-own-use/tree/master/Loon 用我这个整理过的吧

好的好的，非常感谢，我试试

**Comment by czmecho** [comment]
https://github.com/blackmatrix7/ios_rule_script/tree/master/script/zhihu
这里的知乎去广告规则比较全面。

**Comment by hazxy** [comment]
> https://github.com/blackmatrix7/ios_rule_script/tree/master/script/zhihu
> 这里的知乎去广告规则比较全面。

好的，谢谢
