### ISSUE TITLE
快看漫画使用腾讯云函数签到问题

### ISSUE THREAD

**Issue by DoveBoy** [NobyDa/Script#209]
已知用快看漫画脚本使用本地nodejs（14.13.1版本）可以正常运行（图一），但是放到云函数nodejs（12.16版本）运行后，输出结果和本地运行的结果不一样，应该是没有成功（图二），能帮忙看下是什么原因吗？

- 图一

![image](https://user-images.githubusercontent.com/19201447/95649989-58617c00-0b13-11eb-9d40-4afcb1e03751.png)

- 图二

![image](https://user-images.githubusercontent.com/19201447/95650008-6a431f00-0b13-11eb-9972-bc2ab482af44.png)

**Comment by NobyDa** [comment]
@DoveBoy 这报错看起来是没有文件写入权限, 把脚本第73, 108, 109行删除即可.
由于该脚本依赖文件系统, 删除后将无法判断今日是否重复签到.

**Comment by DoveBoy** [comment]
@NobyDa 直接注释掉73，108,109行后，运行只有一大串代码了，其他什么也没有了，只能等明天看看这样是不是成功了。除了这样还有没有别的办法能解决的？实在不想在本地运行
![image](https://user-images.githubusercontent.com/19201447/95656121-b22b6b80-0b3e-11eb-9ae7-391d6750bd7a.png)

**Comment by NobyDa** [comment]
![image](https://user-images.githubusercontent.com/53217160/95657445-24a04980-0b47-11eb-8837-4f714e600201.png)
![image](https://user-images.githubusercontent.com/53217160/95657464-2ff37500-0b47-11eb-880e-cad560f4ae95.png)

@DoveBoy 是不是注释错了, 去掉这几行不会影响正常运行. 多试几遍.

**Comment by DoveBoy** [comment]
@NobyDa 检查了一下注释的位置没有错，不知道是不是不能注释，直接删除后运行正常了
![image](https://user-images.githubusercontent.com/19201447/95657724-91681380-0b48-11eb-896d-f541b5a8350e.png)

**Comment by DoveBoy** [comment]
@NobyDa 大佬能不能给每一个可以使用nodejs运行的脚本添加一下server酱消息推送功能的支持？方便使用云函数的人接收日志消息，每天都去登录云函数查看日志真的太麻烦了

**Comment by balabachao** [comment]
这个我这边已经做到了 iOS端的话用bark这个app 获得一个http推送链接 再再jd签到脚本里面写一个方法 将签到日志 推送到设备
目前已经正常运行好几天了 之前我也想过用server酱 但是微信的server酱通知来了无法直接预览消息 于是我选择了bark
你如果想弄的话我可以教你 或者让作者开一下

DoveBoy <notifications@github.com>于2020年10月16日 周五18:55写道：

**Comment by balabachao** [comment]
[](url)
![image](https://user-images.githubusercontent.com/38938679/96252465-9d3e5480-0fe4-11eb-979f-1b16abfaf880.png)

**Comment by DoveBoy** [comment]
@balabachao 可惜我不是iOS，只能用Android直接跑nodejs或者云函数以及GitHub action的方式

**Comment by NobyDa** [comment]
@DoveBoy @balabachao 暂缓bark与server酱推送的支持, 目前我没有这个需求; 支持node.js的初衷仅仅是为了方便调试.
