### ISSUE TITLE
签到账户二，不设置还是会执行

### ISSUE THREAD

**Issue by Eatiler** [NobyDa/Script#212]
更新了10/15发布的版本后 。
账户二不设置cookie都会自动执行了。
‼️京东转盘-查询发生错误
‼️名称: Error
‼️描述: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]

**Comment by NobyDa** [comment]
那是因为你填过账号2的cookoe，自行按脚本内注释清除

**Comment by Eatiler** [comment]
我忽略到node.js环境下生成的`CookieSet.json`文件。
我以为JD_DailyBonus.js中
```
var Key = ''; 

var DualKey = ''; 
```
如果设置了参数，优先级会比CookieSet.json的更高。

**Comment by NobyDa** [comment]
> 我忽略到node.js环境下生成的`CookieSet.json`文件。
> 我以为JD_DailyBonus.js中
> ```
> var Key = ''; 
> 
> var DualKey = ''; 
> ```
> 如果设置了参数，优先级会比CookieSet.json的更高。

1. cookie字段的参数会自动保存本地以解决更新脚本被覆盖的问题。

2. 如果设置了参数，那将优先使用参数并写入本地；如果为空，则尝试读取本地cookie，存在则执行。

**Comment by cdsxxxx** [comment]
> > 我忽略到node.js环境下生成的`CookieSet.json`文件。
> > 我以为JD_DailyBonus.js中
> > ```
> > var Key = ''; 
> > 
> > var DualKey = ''; 
> > ```
> > 
> > 
> > 如果设置了参数，优先级会比CookieSet.json的更高。
> 
> 1. cookie字段的参数会自动保存本地以解决更新脚本被覆盖的问题。
> 2. 如果设置了参数，那将优先使用参数并写入本地；如果为空，则尝试读取本地cookie，存在则执行。

hello 请问下 quanx里边用的是rewrite_local ，那么怎么删除第二个账号的cookie呢？

**Comment by Eatiler** [comment]
> > > 我忽略到node.js环境下生成的`CookieSet.json`文件。
> > > 我以为JD_DailyBonus.js中
> > > ```
> > > var Key = ''; 
> > > 
> > > var DualKey = ''; 
> > > ```
> > > 
> > > 
> > > 如果设置了参数，优先级会比CookieSet.json的更高。
> > 
> > 
> > 
> > 1. cookie字段的参数会自动保存本地以解决更新脚本被覆盖的问题。
> > 2. 如果设置了参数，那将优先使用参数并写入本地；如果为空，则尝试读取本地cookie，存在则执行。
> 
> hello 请问下 quanx里边用的是rewrite_local ，那么怎么删除第二个账号的cookie呢？

我是自己写了一个node应用结合企业微信去调用 这个脚本哦。还没使用过quanx
