### ISSUE TITLE
建议加入推送消息，目前我所有的脚本都改造了放在服务器 使用pm2 运行着/再配合node-schedule实现定时任务

### ISSUE THREAD

**Issue by braless** [NobyDa/Script#213]
在使用nodejs的脚本里面加入这行可以让手机收到签到得到金豆的日志作者可以考虑一下
 var request = require('request');
var push_key = '  '; //Barkapp推送消息到iOS设备
//

function pushMessage(title, body) {
	var url = 'https://api.day.app/' + push_key + '/' + title + '/' + body;//body既为签到日志  //title 为标题
	request({
			url: encodeURI(url),
			method: "POST",
			json: true,
			headers: {
				"content-type": "application/json",
			}
		},
		function(error, response, body) {
			if (!error) {
				console.log("Bark消息推送成功") // 请求成功的处理逻辑
			} else {
				console.log(error)
			}
		});
}

**Comment by Eatiler** [comment]
我是自己结合了企业微信应用来达到推送目的。你也可以试试

**Comment by mengshouer** [comment]
需求推送+1，如果自己手动改的话，这边更新脚本还不能直接pull。每次更新都需要手动修改(
个人希望增加推送服务[Server酱](http://sc.ftqq.com)

**Comment by bao3** [comment]
推送？我的QX 一直都有通知。你们不是用手机签到？

**Comment by idayske** [comment]
这个需求+1  也希望server酱

**Comment by servicehost** [comment]
支持一下，同样希望加入Server酱的推送功能。正在别的设备上跑，不是手机。

**Comment by jk76cn** [comment]
> 推送？我的QX 一直都有通知。你们不是用手机签到？

我qx也没推送 不知道为什么

**Comment by zhangsean** [comment]
Server酱里面还是要添加企业微信或者钉钉群机器人，何不直接调用钉钉机器人通知？
目前我在OpenWrt上跑JD签到，添加了Server酱通道消息，然后在Server酱添加了钉钉机器人每天给我钉钉发通知的。
我觉得可以直接调用钉钉机器人最好了。
https://github.com/zhangsean/openwrt-packages

**Comment by xxc4869** [comment]
> 在使用nodejs的脚本里面加入这行可以让手机收到签到得到金豆的日志作者可以考虑一下
> var request = require('request');
> var push_key = ' '; //Barkapp推送消息到iOS设备
> //
> 
> function pushMessage(title, body) {
> var url = 'https://api.day.app/' + push_key + '/' + title + '/' + body;//body既为签到日志 //title 为标题
> request({
> url: encodeURI(url),
> method: "POST",
> json: true,
> headers: {
> "content-type": "application/json",
> }
> },
> function(error, response, body) {
> if (!error) {
> console.log("Bark消息推送成功") // 请求成功的处理逻辑
> } else {
> console.log(error)
> }
> });
> }

直接用bark 会报500错误，"push failed: APNS push failed: PayloadTooLarge"，你的会吗，转server酱的bark消息通道就正常

**Comment by xxc4869** [comment]
> 在使用nodejs的脚本里面加入这行可以让手机收到签到得到金豆的日志作者可以考虑一下
> var request = require('request');
> var push_key = ' '; //Barkapp推送消息到iOS设备
> //
> 
> function pushMessage(title, body) {
> var url = 'https://api.day.app/' + push_key + '/' + title + '/' + body;//body既为签到日志 //title 为标题
> request({
> url: encodeURI(url),
> method: "POST",
> json: true,
> headers: {
> "content-type": "application/json",
> }
> },
> function(error, response, body) {
> if (!error) {
> console.log("Bark消息推送成功") // 请求成功的处理逻辑
> } else {
> console.log(error)
> }
> });
> }

直接用bark 会报500错误，"push failed: APNS push failed: PayloadTooLarge"，你的会吗，转server酱的bark消息通道就正常

**Comment by Chandler-Lu** [comment]
在没新增 feature 之前提个个人建议：
`node test.js > /var/www/xxx`，其中 xxx 是个 web 目录
然后有事没事浏览器看一下 log 就好了。。
毕竟每天定时推个消息，我个人觉的怪烦人的😂

**Comment by AsunaEmiria** [comment]
这个其实可以通过第三方js文件实现  
   https://github.com/NobyDa/Script/issues/213#issuecomment-852664366

**Comment by Chandler-Lu** [comment]
> 这个其实可以通过第三方js文件实现
> https://github.com/ruicky/jd_sign_bot/tree/dev

神特么，居然还有这东西

**Comment by xxc4869** [comment]
> 在没新增 feature 之前提个个人建议：
> 
> `node test.js > /var/www/xxx`，其中 xxx 是个 web 目录
> 
> 然后有事没事浏览器看一下 log 就好了。。
> 
> 毕竟每天定时推个消息，我个人觉的怪烦人的😂
> 
> 
> 
> 而且也不能保证所有脚本作者都愿意加推送系统

不看的话有时候cookie过期你也不知道

**Comment by Chandler-Lu** [comment]
> > 在没新增 feature 之前提个个人建议：
> > `node test.js > /var/www/xxx`，其中 xxx 是个 web 目录
> > 然后有事没事浏览器看一下 log 就好了。。
> > 毕竟每天定时推个消息，我个人觉的怪烦人的😂
> > 而且也不能保证所有脚本作者都愿意加推送系统
> 
> 不看的话有时候cookie过期你也不知道

其实京东发现当天没有金豆收入就可以判定了😂

**Comment by xxc4869** [comment]
> > > 在没新增 feature 之前提个个人建议：
> 
> > > `node test.js > /var/www/xxx`，其中 xxx 是个 web 目录
> 
> > > 然后有事没事浏览器看一下 log 就好了。。
> 
> > > 毕竟每天定时推个消息，我个人觉的怪烦人的😂
> 
> > > 而且也不能保证所有脚本作者都愿意加推送系统
> 
> > 
> 
> > 不看的话有时候cookie过期你也不知道
> 
> 
> 
> 其实京东发现当天没有金豆收入就可以判定了😂
我现在都是用圈x和docker跑了

**Comment by Chandler-Lu** [comment]
> > > 在没新增 feature 之前提个个人建议：
> 
> > > `node test.js > /var/www/xxx`，其中 xxx 是个 web 目录
> 
> > > 然后有事没事浏览器看一下 log 就好了。。
> 
> > > 毕竟每天定时推个消息，我个人觉的怪烦人的😂
> 
> > > 而且也不能保证所有脚本作者都愿意加推送系统
> 
> > 
> 
> > 不看的话有时候cookie过期你也不知道
> 
> 其实京东发现当天没有金豆收入就可以判定了😂
> 我现在都是用圈x和docker跑了

嘛，自己用起来觉得方便就好啦
