### ISSUE TITLE
发现wx小程序里面有一个签到京豆

### ISSUE THREAD

**Issue by chermy** [NobyDa/Script#216]
用的lightproxy加电脑版微信进行抓包, 抓到了一个签到和两个查询. 

_**https://wxa.jd.com/wq.jd.com/activep3/singjd/DrawQuery?sactive=xsign_2019_liebianxcx201025&sId=&formid=undefined&g_ty=ls&g_tk=1803216101**_
> request:
 
host: wxa.jd.com
cookie: 
user-agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36 MicroMessenger/7.0.9.501 NetType/WIFI MiniProgramEnv/Windows WindowsWechat
content-type: application/json
wqreferer: http://wq.jd.com/wxapp/pages/bean/index/index
referer: https://servicewechat.com/wx91d27dbf599dff74/473/page-frame.html
accept-encoding: gzip

> response: 

try{ DrawQuery({"award":[{"active":"xsign_bean_qiandaoxcx202009","env":"x","level":1,"time":1603613144}],"helpret":3,"level":1,"now":1603613143,"pic":"头像","ret":0,"retmsg":"OK","sId":"77d***************c05","signpeople":[{"iSHead":1,"nic":"昵称","pic":"头像","time":1603613143}],"sixorfour":4,"status":2}
);}catch(e){}

_**https://wxa.jd.com/wq.jd.com/active/queryprizedetails?actives=jdsign_bean_10_qiandao1904%2Cxsign_2019_liebianxcx201025%2Cxsign_bean_qiandaoxcx202009&g_ty=ls&g_tk=1803216101**_
> request:
 
host: wxa.jd.com
cookie: 
user-agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36 MicroMessenger/7.0.9.501 NetType/WIFI MiniProgramEnv/Windows WindowsWechat
content-type: application/json
wqreferer: http://wq.jd.com/wxapp/pages/bean/index/index
referer: https://servicewechat.com/wx91d27dbf599dff74/473/page-frame.html
accept-encoding: gzip
> response: 
 
try{QueryPrizesDetails({"errmsg":"","result":[{"active":"jdsign_bean_10_qiandao1904","prizes":[],"status":101},{"active":"xsign_2019_liebianxcx201025","prizes":[{"BizType":"","ConstraintTime":"","CouponTime":"","Desc":"25京豆","DiscountQuota":"25,0","Level":1,"Name":"25京豆","PicUrl":"","PrizeTime":"","Reserve":"","Type":4,"UseUrl":"","ValidType":"","Vender":""}],"status":0},{"active":"xsign_bean_qiandaoxcx202009","prizes":[{"BizType":"","ConstraintTime":"","CouponTime":"","Desc":"京豆3个","DiscountQuota":"3,0","Level":1,"Name":"3京豆","PicUrl":"","PrizeTime":"","Reserve":"","Type":4,"UseUrl":"","ValidType":"","Vender":""}],"status":0}],"retcode":0});}catch(e){}

**_https://wxa.jd.com/wq.jd.com/user/info/QueryJDUserInfo?_=1776688424&g_ty=ls&g_tk=1803216101_**
> request:
 
host: wxa.jd.com
cookie: 
user-agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36 MicroMessenger/7.0.9.501 NetType/WIFI MiniProgramEnv/Windows WindowsWechat
content-type: application/json
wqreferer: http://wq.jd.com/wxapp/pages/bean/index/index
referer: https://servicewechat.com/wx91d27dbf599dff74/473/page-frame.html
accept-encoding: gzip
> response: 
 
{"base":{"TipUrl":"http://wqs.jd.com/my/accountv2.shtml?sceneid=11110&state=0&rurl=://wqs.jd.com/my/indexv2.shtml","accountType":0,"curPin":"京东登录名","headImageUrl":"头像","isJTH":"0","jdNum":int京豆值,"jvalue":int京享值,"levelName":"银牌用户","mobile":"手机号****手机号","nickname":"京东昵称","userLevel":61},"definePin":0,"isHitArea":1,"isHomeWhite":0,"isLongPwdActive":0,"isPlusVip":false,"isRealNameAuth":true,"isShortPwdActive":1,"msg":"success.","orderFlag":1,"retcode":0,"userFlag":1}

**Comment by NobyDa** [comment]
wx京东的cookie与脚本所获取的京东cookie不通用, 而且这些请求看起来不是签到的.
