### ISSUE TITLE
jd金融的几个领取链接

### ISSUE THREAD

**Issue by sxx1314** [NobyDa/Script#217]
1. 10京豆 
https://uf.jr.jd.com/up/phone2/phone2.html?actCode=82FBDBF455
2. 1京豆
https://uf.jr.jd.com/up/redEnvelopes/index.html?actCode=890418F764
3. 3京豆
https://uf1.jr.jd.com/up/redEnvelopes/index.html?actCode=3A3E839252
4. 1京豆
https://u2.jr.jd.com/downloadApp/index.html?id=6285&activityId=3537

**Comment by sxx1314** [comment]
每天可领。第一个链接确保cookie登录正常的情况下 可直接获取10豆。不用填手机号码。

**Comment by NobyDa** [comment]
2 3 4 不早加进脚本里了么, 1的话需要手机号, 脚本内所使用的cookie不可直接领取所以没加.
