### ISSUE TITLE
52pojie nodejs 报dns错误

### ISSUE THREAD

**Issue by YaoShuwei** [NobyDa/Script#221]
`(node:10958) ExperimentalWarning: The dns.promises API is experimental
(node:10958) ExperimentalWarning: Readable[Symbol.asyncIterator] is an experimental feature. This feature could change at any time
Response code 403 (Forbidden)

吾爱破解
签到请求失败 ‼️‼️
Response code 403 (Forbidden)`

**Comment by NobyDa** [comment]
返回403是因为吾爱服务器把签到停了, 一般开放注册就会停几天签到
