### ISSUE TITLE
签到脚本今天突然就获取失败了

### ISSUE THREAD

**Issue by DuckRaiser** [NobyDa/Script#223]
我已经把cookie重新获取了，脚本也重新挂在 但运行的结果还是一样 很迷惑
![412CC1D2-26DB-42A8-8602-0872F0938609](https://user-images.githubusercontent.com/52232447/98319916-c7e85f80-201c-11eb-8d77-19dc0b0a4f23.png)

**Comment by DuckRaiser** [comment]
其他用到您的cookie模块的京东任务比如星推官的都运行正常

**Comment by NobyDa** [comment]
脚本内 var ReDis = false 改成 var ReDis = true 然后运行一遍;
目前在脚本第99行 (v1.81)
