### ISSUE TITLE
新的京东签到，望追加

### ISSUE THREAD

**Issue by winxp0621** [NobyDa/Script#224]
活动地址https://jddx.jd.com/m/money/cash.html

**Comment by NobyDa** [comment]
入口在哪, 这领的红包是小金库红包么, 感觉没什么用

**Comment by winxp0621** [comment]
入口找不到了，没用的话把这个签到加上吧，里面还有个抽奖
地址: https://jdda.jd.com/app/hd/#/gachakon

**Comment by winxp0621** [comment]
满额可提现到小金库
