### ISSUE TITLE
获取cookie失败

### ISSUE THREAD

**Issue by EchoChan314** [NobyDa/Script#225]
不管是用QX还是loon，访问https://bean.m.jd.com 点击签到并且出现签到日历并没有出现弹窗，
已经确定mitm已开启，hostname也添加了，https:\/\/api\.m\.jd\.com\/client\.action.*functionId=signBean url script-request-header https://raw.githubusercontent.com/NobyDa/Script/master/JD-DailyBonus/JD_DailyBonus.js 也确定没缺失。
希望开发者解决一下，谢谢。

**Comment by NobyDa** [comment]
经过测试, 没有任何问题.
自行检查一下证书, 日志或相关请求是否命中脚本.

**Comment by EchoChan314** [comment]
抓包是这个请求，https://api.m.jd.com/client.action?functionId=signBeanGroupStageIndex&body=%7B%22monitor_refer%22%3A%22%22%2C%22rnVersion%22%3A%223.9%22%2C%22fp%22%3A%22-1%22%2C%22shshshfp%22%3A%22-1%22%2C%22shshshfpa%22%3A%22-1%22%2C%22referUrl%22%3A%22-1%22%2C%22userAgent%22%3A%22-1%22%2C%22jda%22%3A%22-1%22%2C%22monitor_source%22%3A%22bean_m_bean_index%22%7D&appid=ld&client=apple&clientVersion=null&networkType=&osVersion=&uuid=&jsonp=jsonp_1604933716077_18378 按理应该匹配到脚本的呢

**Comment by Youmio** [comment]
请问最后是咋解决的呢
