### ISSUE TITLE
surge mac使用b站自动切换地区js的问题

### ISSUE THREAD

**Issue by LSSCP** [NobyDa/Script#239]
手动在autobiliregion切换线路是能观看的.说明规则和线路都是有效的.
所以不清楚是什么导致的无法自动切换.

还是只能在ios上使用?

boxjs里的设定:
<img width="342" alt="image" src="https://user-images.githubusercontent.com/21199343/99470578-ea18a080-297f-11eb-8647-11b9632a4875.png">

软件版本:
osx:11
surge Mac 4

surge 相关配置:
[Proxy Group]
TW = select, V2-TW01, V2-TW02
HK = select, V2-HK01, V2-HK02
AutoBiliRegion = select, DIRECT, HK, TW

[Script]
Bili Region = type=http-response,pattern=https:\/\/api\.bilibili\.com\/pgc\/view\/app\/season\?access_key,requires-body=1,max-size=0,control-api=1,script-path=https://raw.githubusercontent.com/NobyDa/Script/master/Surge/JS/Bili_Auto_Regions.js

[Rule]
DOMAIN-SUFFIX,biliapi.net,AutoBiliRegion
DOMAIN,api.bilibili.com,AutoBiliRegion
DOMAIN,www.bilibili.com,AutoBiliRegion
DOMAIN,upos-hz-mirrorakam.akamaized.net,AutoBiliRegion
[MitM]
hostname = api.bilibili.com

**Comment by NobyDa** [comment]
已尝试兼容Surge Mac, 更新脚本以及匹配URL再试试.

**Comment by LSSCP** [comment]
> 已尝试兼容Surge Mac, 更新脚本以及匹配URL再试试.

刚更新后发现没效果,是不是要触发问题?
不是很懂具体代码.

比如我目前默认策略是direct,去打开港澳台资源的时候发起请求也是用本地ip发起的,所以服务器就直接返回一个错误,然后压根就不会触发rewrite那个请求地址?

**Comment by NobyDa** [comment]
> > 已尝试兼容Surge Mac, 更新脚本以及匹配URL再试试.
> 
> 刚更新后发现没效果,是不是触发地址的问题?
> 不是很懂具体代码.
> 
> 比如我目前默认策略是direct,去打开港澳台资源的时候发起请求也是用本地ip发起的,所以服务器就直接返回一个错误,然后压根就不会触发rewrite那个请求地址?

由于手上没有Mac设备, 无法详细的调试.
无效也没办法了, 用油猴脚本代替吧.

**Comment by LSSCP** [comment]
网上有个油猴脚本,打开港澳台页面404后,然后通过他提供的代理去把播放页面拉回来之类的吧.毕竟播放地址本身不限制ip.

https://github.com/ipcjs/bilibili-helper

**Comment by LSSCP** [comment]
好的,辛苦了,那先关闭好了
