### ISSUE TITLE
建议延时做任务

### ISSUE THREAD

**Issue by jw10126121** [NobyDa/Script#243]
延迟一个随机时间执行任务，防止做任务领取京豆的时间太短，会出问题。最好延迟的时间是一定范围的随机值。

**Comment by JieMin-T** [comment]
大佬  遍历数据库数据库  执行失败

var mysql = require('mysql');

var connection = mysql.createConnection({
    host: '127.0.0.1',
    user: 'root',
    password: 'admin',
    port: '3306',
    database: 'jd_sign'
});

connection.connect(function (err) {
    if (err) throw err;
    console.log("Connected!");
});


var sql = 'SELECT Cookie FROM jd_cookie';

connection.query(sql, function (err, result) {
    if (err) {
        console.log('[SELECT ERROR] - ', err.message);
        return;
    }

  function sleep(numberMillis) {
    var now = new Date();
    var exitTime = now.getTime() + numberMillis;
    while (true) {
      now = new Date();
      if (now.getTime() > exitTime)
        return;
    }
  }

    for (j = 0; j < result.length; j++) {
        var Key = result[j].Cookie
        console.log('--------------------------SELECT----------------------------');
        console.log(Key);
        console.log('------------------------------------------------------------\n\n');
        sleep(5000);
