### ISSUE TITLE
双签完成后的奖励京豆没有自动领取

### ISSUE THREAD

**Issue by servicehost** [NobyDa/Script#248]
RT，现在京东和金融双签完成后的奖励京豆不能自动领取，需要手动进入领取。

盼修复，谢谢。

**Comment by NobyDa** [comment]
早上再签一次试试看

**Comment by servicehost** [comment]
> 
> 
> 早上再签一次试试看

今天测试了，上午9点多这会又重新跑了一次脚本，双签奖励依然无法领取。手动领取正常。

**Comment by servicehost** [comment]
脚本版本 v1.87

**Comment by yufeiyang2008** [comment]
手动去京东金融签一下第二天就可以自己领了

**Comment by servicehost** [comment]
> 
> 
> 手动去京东金融签一下第二天就可以自己领了

不太理解，是指先不用脚本来跑，手动去一次金融签到后，从此以后脚本就不能自动双签领奖励了？

还是说总要每天手动去金融签一下，然后脚本才会自动领双签奖励？要是这样那跑脚本还有什么意义？

**Comment by yufeiyang2008** [comment]
脚本签过了后，去app领一下

**Comment by servicehost** [comment]
> 
> 
> 脚本签过了后，去app领一下

醉了.... 我现在就是这么做的，而提出的这个 Issues 就是为了想解决这个问题....  因为过去是无需这么的

上面我写的原文也写了：“需要手动进入领取”，我当然知道手动去APP领，麻烦理解下逻辑。

**Comment by yufeiyang2008** [comment]
是你自己理解不了，又不是让你天天去app领

**Comment by servicehost** [comment]
> 
> 
> 是你自己理解不了，又不是让你天天去app领

是你说的不清楚好吧？我上文还仔细问了一下你，是哪种方案？
A：领一次后，将来脚本就能自动领取奖励了？
B：还是每天都需要手动去金融领一下，然后脚本才会自动领双签奖励？

你就回答一个：脚本签过了后，去app领一下。

这不答非所问吗？试问 谁能明白你是什么意思？

**Comment by yufeiyang2008** [comment]
像你这种智商还是别玩openwrt了

**Comment by servicehost** [comment]
> 
> 
> 像你这种智商还是别玩openwrt了

嗯，您的智商高，说的逻辑一塌糊涂，还要指责别人智商低。你可真聪明，IQ一定是200以上。除您以外都是蠢货，您openwrt都玩的非常厉害，我太钦佩您。

**Comment by NobyDa** [comment]
@servicehost 部分用户可能会遇到这个问题, 原因可能是部分账号的旧双签接口没有迁移到新接口导致的, 而且双签接口有多个, 所以导致了有的用户都能签成功, 而有的用户可能只能成功一俩个. 新版本正在尝试解决, 更新脚本再试试看.

**Comment by servicehost** [comment]
> @servicehost 部分用户可能会遇到这个问题, 原因可能是部分账号的旧双签接口没有迁移到新接口导致的, 而且双签接口有多个, 所以导致了有的用户都能签成功, 而有的用户可能只能成功一俩个. 新版本正在尝试解决, 更新脚本再试试看.

OK，已更新至v1.88版，待明天反馈结果。

**Comment by servicehost** [comment]
@NobyDa v1.88版双签领取已正常，问题解决。
