### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Arrogance-H** [NobyDa/Script#251]
名称：Error
描述：No NDS results
日志：
2020/12/13 01:05:04:289  <console>    [JS Console]: 
‼️京东转盘-查询发生错误
‼️名称: Error
‼️描述: No DNS results
2020/12/13 01:05:04:305  <console>    [JS Console]: 
‼️京东魔方-查询发生错误
‼️名称: Error
‼️描述: No DNS results
2020/12/13 01:05:04:320  <console>    [JS Console]: 
‼️京东商城-京豆发生错误
‼️名称: Error
‼️描述: No DNS results
2020/12/13 01:05:04:336  <console>    [JS Console]: 
‼️京东发现-看看发生错误
‼️名称: Error
‼️描述: No DNS results
2020/12/13 01:05:04:350  <console>    [JS Console]: 
‼️京东商城-超市发生错误
‼️名称: Error
‼️描述: No DNS results
2020/12/13 01:05:04:365  <console>    [JS Console]: 
‼️京东商城-直播发生错误
‼️名称: Error
‼️描述: No DNS results
2020/12/13 01:05:04:381  <console>    [JS Console]: 
‼️京东商城-闪购发生错误
‼️名称: Error
‼️描述: No DNS results
2020/12/13 01:05:04:396  <console>    [JS Console]: 
‼️京东商城-国际发生错误
‼️名称: Error
‼️描述: No DNS results
2020/12/13 01:05:04:412  <console>    [JS Console]: 
‼️京东现金-红包发生错误
‼️名称: Error
‼️描述: No DNS results
2020/12/13 01:05:04:435  <console>    [JS Console]: 
‼️京东商城-现金发生错误
‼️名称: Error
‼️描述: No DNS results
2020/12/13 01:05:04:450  <console>    [JS Console]: 
‼️京东商城-摇摇发生错误
‼️名称: Error
‼️描述: No DNS results
2020/12/13 01:05:04:464  <console>    [JS Console]: 
‼️京东秒杀-查询发生错误
‼️名称: Error
‼️描述: No DNS results
2020/12/13 01:05:04:497  <console>    [JS Console]: 
‼️京东金融-签贰发生错误
‼️名称: Error
‼️描述: No DNS results
2020/12/13 01:05:04:511  <console>    [JS Console]: 
‼️京东金融-签叁发生错误
‼️名称: Error
‼️描述: No DNS results
2020/12/13 01:05:04:527  <console>    [JS Console]: 
‼️京东金融-签肆发生错误
‼️名称: Error
‼️描述: No DNS results
2020/12/13 01:05:04:543  <console>    [JS Console]: 
‼️京东金融-签伍发生错误
‼️名称: Error
‼️描述: No DNS results
2020/12/13 01:05:07:820  <console>    [JS Console]: 
‼️京东商城-内衣发生错误
‼️名称: Error
‼️描述: No DNS results
2020/12/13 01:05:07:839  <console>    [JS Console]: 
‼️京东商城-鞋靴发生错误
‼️名称: Error
‼️描述: No DNS results
2020/12/13 01:05:07:864  <console>    [JS Console]: 
‼️京东日历-翻牌发生错误
‼️名称: Error
‼️描述: No DNS results
2020/12/13 01:05:07:885  <console>    [JS Console]: 
‼️京东晚市-补贴发生错误
‼️名称: Error
‼️描述: No DNS results
2020/12/13 01:05:07:907  <console>    [JS Console]: 
‼️京东商城-医药发生错误
‼️名称: Error
‼️描述: No DNS results

**Comment by NobyDa** [comment]
自行检查DNS配置.

**Comment by NobyDa** [comment]
自行检查DNS配置.
