### ISSUE TITLE
日志显示奇怪的错误

### ISSUE THREAD

**Issue by John1215** [NobyDa/Script#256]
‼️Node.js持久化读取发生错误
‼️名称: SyntaxError
‼️描述: Unexpected end of JSON input

‼️Node.js持久化读取发生错误
‼️名称: SyntaxError
‼️描述: Unexpected end of JSON input

如上，日志里面很多这个错误，正常吗？如何解决？

**Comment by NobyDa** [comment]
Node.js环境下没有太大影响, 持久化是用来存cookie的, 避免更新脚本cookie被删除.
试一试删除脚本文件目录下的CookieSet.json文件.

**Comment by John1215** [comment]
> Node.js环境下没有太大影响, 持久化是用来存cookie的, 避免更新脚本cookie被删除.
> 试一试删除脚本文件目录下的CookieSet.json文件.

谢谢大佬，搞定了，我用find找了一下，发现 www 和 www/cgi-bin/ 下不知道什么时候冒出来的CookieSet.json文件，还是0KB大小，不知道哪来的，这两和脚本目录底下那个一起删了，已经正常
