### ISSUE TITLE
京东签到改版

### ISSUE THREAD

**Issue by fangpidedongsun** [NobyDa/Script#260]
京东签到改版
https://bean.m.jd.com
不出现签到日历，无法获取CK

**Comment by NobyDa** [comment]
> 京东签到改版
> https://bean.m.jd.com
> 不出现签到日历，无法获取CK

https://bean.m.jd.com/bean/signIndex.action

**Comment by fangpidedongsun** [comment]
> > 京东签到改版
> > https://bean.m.jd.com
> > 不出现签到日历，无法获取CK
> 
> https://bean.m.jd.com/bean/signIndex.action
搞定！
