### ISSUE TITLE
JD获取不了cookie

### ISSUE THREAD

**Issue by yiyaahui** [NobyDa/Script#263]
直接到日历页面一直尝试都不行。

**Comment by SStarbuckS** [comment]
bean.m.jd.com

**Comment by ID404** [comment]
bean.m.jd.com现在自动跳转到h5.m.jd.com了

**Comment by NobyDa** [comment]
正确添加Rewrite后再登录 https://bean.m.jd.com/bean/signIndex.action 亲测没问题.

**Comment by yiyaahui** [comment]
> 正确添加Rewrite后再登录 https://bean.m.jd.com/bean/signIndex.action 亲测没问题.

Rewrite没更新。已OK。感谢指正

**Comment by bao3** [comment]
> > 正确添加Rewrite后再登录 https://bean.m.jd.com/bean/signIndex.action 亲测没问题.
> 
> Rewrite没更新。已OK。感谢指正

主动 close 一下吧。
