### ISSUE TITLE
取消店铺与商品收藏

### ISSUE THREAD

**Issue by L1cardo** [NobyDa/Script#264]
能否添加取消店铺与商品收藏的脚本？

**Comment by NobyDa** [comment]
https://raw.githubusercontent.com/LXK9301/jd_scripts/master/jd_unsubscribe.js

**Comment by bao3** [comment]
> https://raw.githubusercontent.com/LXK9301/jd_scripts/master/jd_unsubscribe.js

@NobyDa  Error 404 . 。 这个整个源都删除了。

**Comment by NobyDa** [comment]
> > https://raw.githubusercontent.com/LXK9301/jd_scripts/master/jd_unsubscribe.js
> 
> @NobyDa  Error 404 . 。 这个整个源都删除了。

https://gitee.com/lxk0301/jd_scripts/raw/master/jd_unsubscribe.js

**Comment by L1cardo** [comment]
其实surge订阅了您的模组，希望可以加入到您的模组里面
实在不行我自己另外添加脚本也行
