### ISSUE TITLE
大佬，微博去广告的是失效了吗

### ISSUE THREAD

**Issue by CANBAAA** [NobyDa/Script#267]
Script/QuantumultX/File/ 下的两个wb js

**Comment by NobyDa** [comment]
这俩脚本的原作者已经停止更新了, 可能已失效.

**Comment by 26675502** [comment]
大佬   为什么我会收到这个邮件   是因为关注你的库的原因吗？

**Comment by NobyDa** [comment]
> 大佬 为什么我会收到这个邮件 是因为关注你的库的原因吗？

是的, 因为你点了watch
