### ISSUE TITLE
关于京东多账号的问题

### ISSUE THREAD

**Issue by shouyiyangwencong** [NobyDa/Script#270]
大佬您好，我用lxk0301大佬的脚本获取了第三个京东cookie，然而三个账号的脚本运行只适合他的京东脚本，如东东农场什么的。至于您的京东多合一签到脚本（2021.01.28更新）却不适用。（只能签到两个账号）想知道是怎么回事。

**Comment by shouyiyangwencong** [comment]
![image](https://user-images.githubusercontent.com/36787644/106685040-8d359980-6602-11eb-8a59-232421adab49.png)

**Comment by shouyiyangwencong** [comment]
![image](https://user-images.githubusercontent.com/36787644/106685051-958dd480-6602-11eb-8cc2-9e6f3eec1ccd.png)

**Comment by NobyDa** [comment]
目前京东签到原版脚本仅支持双账号
