### ISSUE TITLE
wechat脚本失效

### ISSUE THREAD

**Issue by w164955** [NobyDa/Script#274]
WeChat不能屏蔽广告了

**Comment by lzr52o** [comment]
> WeChat不能屏蔽广告了

我的为何还可以？

**Comment by w164955** [comment]
> > WeChat不能屏蔽广告了
> 
> 我的为何还可以？

朋友圈有广告了，WeChat版本：8.0.2 软件：QX

**Comment by NobyDa** [comment]
> > > WeChat不能屏蔽广告了
> > 
> > 
> > 我的为何还可以？
> 
> 朋友圈有广告了，WeChat版本：8.0.2 软件：QX

那个脚本并不是屏蔽朋友圈广告, 而是微信公众号底栏广告.
