### ISSUE TITLE
京东农场

### ISSUE THREAD

**Issue by luanwulin** [NobyDa/Script#283]
自动签到脚本，能不能加上农场~

**Comment by EchoChan314** [comment]
https://jdsharedresourcescdn.azureedge.net/jdresource/jd_fruit.js

**Comment by luanwulin** [comment]
> https://jdsharedresourcescdn.azureedge.net/jdresource/jd_fruit.js

= =大佬，403了

**Comment by EchoChan314** [comment]
> > https://jdsharedresourcescdn.azureedge.net/jdresource/jd_fruit.js
> 
> = =大佬，403了

需要代理，这是https://gitee.com/lxk0301搭建的。
