### ISSUE TITLE
52pojie 失效了吗？

### ISSUE THREAD

**Issue by rklhxyk1128** [NobyDa/Script#286]
一直提示脚本待更新， 还是我没操作对

**Comment by q494961133** [comment]
啥…我怎么收到的这个

这是一封来自昨天的邮件

**Comment by q494961133** [comment]
[mitm]
www.52pojie.cn

[rewrite_local]
# 获取52破解Cookie
https:\/\/www\.52pojie\.cn\/home\.php\? url script-request-header https://raw.githubusercontent.com/NobyDa/Script/master/52pojie-DailyBonus/52pojie.js

[task_local]

# 吾爱签到
0 9 * * * https://raw.githubusercontent.com/NobyDa/Script/master/52pojie-DailyBonus/52pojie.js, tag=吾爱签到, enabled=true

这是一封来自昨天的邮件

**Comment by NobyDa** [comment]
可以正常签到，没什么问题。

**Comment by rklhxyk1128** [comment]
现在可以了，可能那会儿我的IP地址不稳定

**Comment by q494961133** [comment]
我库里不知道啥时候复刻的，版本老，你找新的…

这是一封来自昨天的邮件
