### ISSUE TITLE
京东签到脚本是不是有一些接口有问题

### ISSUE THREAD

**Issue by doggonegod** [NobyDa/Script#287]
https://github.com/NobyDa/Script/blob/master/JD-DailyBonus/JD_DailyBonus.js

有些项目（比如京东金融）显示no dns results,请问这是怎么回事呢？

**Comment by NobyDa** [comment]
字面意思。你所设置的dns提供商无法查询某些京东域名，自然会导致无法连接。
这通常是设置了国外dns导致的。

**Comment by doggonegod** [comment]
> 字面意思。你所设置的dns提供商无法查询某些京东域名，自然会导致无法连接。
> 这通常是设置了国外dns导致的。

非常感谢解答，发现我这边让京东全用了 119.28.28.28 的dns，应该是这个导致的
