### ISSUE TITLE
请问部分项目领取异常是否与“黑号”有关？

### ISSUE THREAD

**Issue by AllForLandlord** [NobyDa/Script#289]
这边用京东多合一脚本签到的时候总有几个项目是“领取异常”，请问这与京东黑号有关吗？

![04A2426A-0470-462E-A0AD-58012731F1C7](https://user-images.githubusercontent.com/68906347/113475560-05a4c380-94a9-11eb-846f-4abe5440281d.jpeg)

**Comment by NobyDa** [comment]
无关。这几个接口很特殊，我也没弄明白领取异常的问题；
一般来说京东老账号领取成功的几率比较高，注册时间不长的账号就完全看运气了。
