### ISSUE TITLE
DOMAIN-SUFFIX,3g.qq.com in AdRule.list

### ISSUE THREAD

**Issue by maxduke** [NobyDa/Script#29]
规则 DOMAIN-SUFFIX,3g.qq.com 会导致 腾讯管家无法更新 来电识别库

**Comment by NobyDa** [comment]
具体的url发一下

**Comment by maxduke** [comment]
https://config.3g.qq.com/qqsecure_config_update/cloudtestnew/2019/11/25/40422.sdbp_20191121054503_20191125072101.zip
