### ISSUE TITLE
zhihu answer.js 在浏览时报错

### ISSUE THREAD

**Issue by wongdean** [NobyDa/Script#30]
报错脚本：
https://raw.githubusercontent.com/onewayticket255/Surge-Script/master/surge%20zhihu%20answer.js
报错信息：
2019/11/25 14:39:51:327  <error>      [JS Console]: Exception {"line":8,"column":13}, TypeError: undefined is not an object (evaluating 'body['data'].forEach'), https://raw.githubusercontent.com/wongdean/Script/master/JS/surge_zhihu_answer.js
环境信息：
iOS 12
quan x 1.0.3

复现条件：
知乎客户端打开一个答案，100%复现

**Comment by NobyDa** [comment]
已更新脚本, 如果非JS订阅用户, 自行把脚本引用换成我的url

**Comment by wongdean** [comment]
非常感谢！测试没有报错了！
