### ISSUE TITLE
配置报错

### ISSUE THREAD

**Issue by zcq100** [NobyDa/Script#304]
Quamtumult X v1.0.21 配置里面加入这个本地重写，提示语法错误。

[rewrite_local]
        # 获取京东Cookie. 
        # 注意此为远程路径, 低版本用户请自行调整为本地路径.
        https:\/\/api\.m\.jd\.com\/client\.action.*functionId=signBean url script-request-header https://raw.githubusercontent.com/NobyDa/Script/master/JD-DailyBonus/JD_DailyBonus.js

**Comment by NobyDa** [comment]
这配置的意思是放在配置文件下的[rewrite_local]段落, 而不是让你直接复制粘贴. 建议查看新手教程.
