### ISSUE TITLE
Bili_Auto_Regions脚本问题

### ISSUE THREAD

**Issue by BBkinga** [NobyDa/Script#307]
ipad，quanx正式版 1.0.22

我在ipad上装iPhone版的bilibili，也就是竖屏版，这个脚本不起作用，只对哔哩哔哩HD版起作用，
请问怎样修改可以使竖屏版也可以自动切换？

**Comment by hechang357** [comment]
为什么我会收到这个邮件？懵------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年6月16日(星期三) 下午2:37
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[NobyDa/Script] Bili_Auto_Regions脚本问题 (#307)

**Comment by NobyDa** [comment]
> 
> 
> ipad，quanx正式版 1.0.22
> 
> 我在ipad上装iPhone版的bilibili，也就是竖屏版，这个脚本不起作用，只对哔哩哔哩HD版起作用，
> 请问怎样修改可以使竖屏版也可以自动切换？

@BBkinga 该脚本未适配iPad客户端

**Comment by NobyDa** [comment]
> 
> 为什么我会收到这个邮件？懵------------------&nbsp;原始邮件&nbsp;------------------ ***@***.***&gt; 发送时间:&nbsp;2021年6月16日(星期三) 下午2:37 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[NobyDa/Script] Bili_Auto_Regions脚本问题 (#307)

@hechang357 可能你watch了本项目吧
