### ISSUE TITLE
TestFlightDownload.sgmodule 这个模块似乎已经失效

### ISSUE THREAD

**Issue by askiter** [NobyDa/Script#308]
你好，

我现在已经无法更新最新的Surge最新TF版本了，提示App不存在或者不可用，可否检查一下

**Comment by NobyDa** [comment]
经测试没有任何问题

**Comment by LagunAPaTa** [comment]
测试了一下在iPadOS上的确失效了 iPadOS版本15.0

**Comment by ashurinn** [comment]
刚刚测试了iPadOS15.0(19A5281j)，可以正常使用。

**Comment by LagunAPaTa** [comment]
感觉应该是apple的问题 我把app删除 然后重新下载就OK了 更新就一直失败
