### ISSUE TITLE
91在surge下无效

### ISSUE THREAD

**Issue by banditlives** [NobyDa/Script#310]
野比大佬，91.js在surge无法突破限制，测试在圈X正常，求解惑

**Comment by NobyDa** [comment]
@banditlives 似乎是Surge的问题, 无法正确区分请求是否为HTTP导致被Tun接管, 进而导致Rewrite等高级功能不可用;
可以试下配置文件加入以下字段:
```
[General]
force-http-engine-hosts = *91*:8080, *my10api*:8080
```
以上端口号可能会改变, 如测试无效则需要自行抓包填写.

**Comment by banditlives** [comment]
> @banditlives 似乎是Surge的问题, 无法正确区分请求是否为HTTP导致被Tun接管, 进而导致Rewrite等高级功能不可用;
> 可以试下配置文件加入以下字段:
> 
> ```
> [General]
> force-http-engine-hosts = *91*:8080, *my10api*:8080
> ```
> 
> 以上端口号可能会改变, 如测试无效则需要自行抓包填写.

Done,老刘背锅
