### ISSUE TITLE
52pojie 还是可以用的

### ISSUE THREAD

**Issue by dukecd33369** [NobyDa/Script#311]
之前脚本 自动获取cookie不行  但是手动写cookie 可以用的

**Comment by NobyDa** [comment]
我刚试了下, 吾爱又取消了校验Cookie里的wzws_cid字段, 前两天是没办法绕过的, 我恢复下脚本吧

**Comment by dukecd33369** [comment]
我用的电脑 查看的Cookie 只写死了htVD_2132_saltkey和htVD_2132_auth 这两个字段 直接就可以用

**Comment by dukecd33369** [comment]
但是脚本里面的获取cookie 好像拿不到这两个字段

**Comment by NobyDa** [comment]
> 但是脚本里面的获取cookie 好像拿不到这两个字段

启用脚本后登陆 https://www.52pojie.cn/home.php 获取, 实测没什么问题。
不过吾爱的cookie有效期非常久，获取一次可以说是一劳永逸。
