### ISSUE TITLE
京东签到失效了么

### ISSUE THREAD

**Issue by Maxize** [NobyDa/Script#314]
扫描二维码一直没有生效，获取不到 token 了。前几天开始就不行了。
用微信扫，微信显示网络异常。
用 jd 扫，提示升级到最新客户端，然后二维码失效了。

**Comment by NobyDa** [comment]
OpenWrt版本么？
该仓库并不维护OpenWrt版京东签到，因为OpenWrt版是基于本项目的另一个分支版本
建议去相关作者github里提issues.
