### ISSUE TITLE
返回的响应 乱码怎么获取的呀

### ISSUE THREAD

**Issue by dukecd33369** [NobyDa/Script#316]
像52破解那个脚本 里面 判断是否签到成功那段 match里面的乱码怎么弄的呀

**Comment by NobyDa** [comment]
当时写这脚本时发现Surge只能以UTF8的方式解码响应体，如果遇到以GBK编码的HTML响应时可能会导致中文乱码。
所以这种情况并没有特别好的解决方案，能想到的只能抓取乱码后的字符串进行无脑匹配。

乱码的中文字符串可以在
https://www.njstar.com/cms/cjk-code-to-unicode-conversion
转换成中文，这是或许是唯一能解码GBK中文乱码的在线转换网址。

**Comment by dukecd33369** [comment]
我怎么抓取乱码后的字符串呐  我用的windows 下 Node.js开发的 cmd跑出来的乱码发现并不能用

**Comment by dukecd33369** [comment]
我试了下 Node.js下可以用 iconv-lite 来解决GBK乱码的问题  但是Quantumult-X和Surge怎么弄呀

**Comment by NobyDa** [comment]
> 
> 
> 我试了下 Node.js下可以用 iconv-lite 来解决GBK乱码的问题 但是Quantumult-X和Surge怎么弄呀

QX和Surge的脚本功能拿到的是“解码后”的响应，而非原始二进制数据，所以没有任何解决方案，请咨询APP开发者。
