### ISSUE TITLE
Loon TF跨域脚本失效

### ISSUE THREAD

**Issue by Nomamuk** [NobyDa/Script#319]
Apple id为国区 安装/更新tf loon会直接断开loon并提示“无法安装Loon”
@NobyDa

**Comment by xfzha** [comment]
我刚试了下正常

**Comment by Nomamuk** [comment]
确实一部分人正常，但tg群里已经很多人反馈失效了> 我刚试了下正常

**Comment by xfzha** [comment]
不好意思我看错题了....我用的是surge，然后tf里有Loon，更新了下Loon没问题我就无脑发表了...实在抱歉

**Comment by xfzha** [comment]
是开着loon更新loon？还是更新其他的也是这样

**Comment by NobyDa** [comment]
> 
> 
> Apple id为国区 安装/更新tf loon会直接断开loon并提示“无法安装Loon”
> @NobyDa

并没有问题，断VPN后提示APP不可用是因为没有执行到脚本，建议咨询Loon开发者。
