### ISSUE TITLE
京东双签不行了么

### ISSUE THREAD

**Issue by xiaopangzia** [NobyDa/Script#321]
京东双签不行了么，没法自动签到

**Comment by ChenEgou** [comment]
是的，不行好几天了

**Comment by zhkufish** [comment]
好像没有人更新维护了.

**Comment by xiaopangzia** [comment]
> 好像没有人更新维护了.

有把，不在主分支维护，点开其他分支还是有更新的

**Comment by ChenEgou** [comment]
> > 好像没有人更新维护了.
> 
> 有把，不在主分支维护，点开其他分支还是有更新的

所以，最近的代码，哪里有？

**Comment by zh-peng** [comment]
双签确实挂了，金融貌似没办法签了
