### ISSUE TITLE
大佬请问一下爱奇艺签到多账号怎么搞？变量分割怎么写？

### ISSUE THREAD

**Issue by Coolrui1816** [NobyDa/Script#322]
如题

**Comment by NobyDa** [comment]
该脚本未加入多账号功能。

建议使用boxjs的"会话切换"；如不理解，可google查找相关教程。

**Comment by pxylen** [comment]
爱奇艺ck有效期比较短 不建议玩多账户

**Comment by Coolrui1816** [comment]
> 该脚本未加入多账号功能。
> 
> 建议使用boxjs的“会话切换”；如不理解，可google查看相关教程。

感谢回复。。知道了

**Comment by Coolrui1816** [comment]
> 爱奇艺CK比较短不建议玩多

感谢回复
