### ISSUE TITLE
请大佬帮忙指点下这个什么问题，谢谢大佬

### ISSUE THREAD

**Issue by bingotun** [NobyDa/Script#327]
![image](https://user-images.githubusercontent.com/58700900/129413344-54c5702e-50c2-4b89-b459-566afbf05522.png)

**Comment by NobyDa** [comment]
应该是获取或手动填写的cookie里缺少关键值吧，提取关键值失败后cookie赋值成undefined，进而导致报错。

没看过具体逻辑，根据报错信息猜的；

另外，该脚本为下游脚本，非本项目脚本不再进行解答；具体可咨询相关作者。
