### ISSUE TITLE
请问一下大家签到有京豆吗？像我这种账号是不是黑了，日志如下：

### ISSUE THREAD

**Issue by u4250** [NobyDa/Script#331]
【签到概览】:  成功27个, 失败5个
【签到奖励】:  11京豆
【其他奖励】:  0.05红包, 0.01金贴, 0.03现金
【账号总计】:  4026京豆, 2.01钢镚
【其他总计】:  0.02金贴, 3.79现金, 0.1红包

京东商城-京豆: 成功, 明细: 2京豆 🐶
京东商城-超市: 成功, 明细: 7京豆 🐶
京东金融-钢镚: 失败, 未获取签到Body ⚠️
京东商城-转盘: 成功, 状态: 未中奖 🐶
京东商城-闪购: 成功, 明细: 2京豆 🐶
京东现金-红包: 失败, 活动太火爆了，还是去买买买吧～！ ⚠️
京东商城-魔方: 失败, 原因: 无机会 ⚠️
京东商城-金贴: 成功, 明细: 0.01金贴 💰
京东商城-现金: 成功, 明细: 0.03现金 💰
京东商城-摇摇: 成功, 明细: 无奖励 🐶
京东商城-摇摇: 多次, 获得满59减10优惠券→ 仅可购买玩具乐器部分商品
京东秒杀-红包: 成功, 明细: 0.05红包 🧧
京东商城-内衣: 成功, 明细: 无京豆 🐶
京东商城-卡包: 成功, 明细: 无京豆 🐶
京东商城-陪伴: 成功, 明细: 无京豆 🐶
京东商城-鞋靴: 成功, 明细: 无京豆 🐶
京东商城-童装: 成功, 明细: 无京豆 🐶
京东商城-母婴: 成功, 明细: 无京豆 🐶
京东商城-数码: 成功, 明细: 无京豆 🐶
京东商城-女装: 成功, 明细: 无京豆 🐶
京东商城-图书: 成功, 明细: 无京豆 🐶
京东金贴-双签: 失败, 原因: 未在京东app签到 ⚠️
京东商城-电竞: 成功, 明细: 无京豆 🐶
京东商城-箱包: 成功, 明细: 无京豆 🐶
京东商城-校园: 成功, 明细: 无京豆 🐶
京东商城-健康: 成功, 明细: 无京豆 🐶
京东拍拍-二手: 成功, 明细: 无京豆 🐶
京东商城-清洁: 成功, 明细: 无京豆 🐶
京东商城-个护: 成功, 明细: 无京豆 🐶
京东商城-家电: 成功, 明细: 无京豆 🐶
京东商城-菜场: 成功, 明细: 无京豆 🐶
金融京豆-双签: 失败, 原因: 未在金融app签到 ⚠️

签到用时: 5.41 秒

**Comment by Jveen-D** [comment]
一样的  我也是二十多个

**Comment by u4250** [comment]
好的 谢谢回复
