### ISSUE TITLE
鸿蒙系统京东app无法扫描二维码获取cookies，提示升级最新版本

### ISSUE THREAD

**Issue by lyjhyjyes** [NobyDa/Script#336]
R2S刷openwrt，运行京东签到插件几个月，一直都是京东app扫二维码获取cookies。
OPENWRT上脚本更新时间: 2021.08.26 21:20 v2.1.2
有效接口: 20+
脚本兼容: QuantumultX, Surge, Loon, JSBox, Node.js
今天cookies到期，手机是华为mate30 5G，京东APP for harmonyos v10.1.2 buuld89760。app里点击检查更新，已经是最新版本。扫二维码一直提示需要升级最新版本。而我之前就是用京东app鸿蒙版本。
请问以后会兼容鸿蒙版本吗

**Comment by NobyDa** [comment]
#332
