### ISSUE TITLE
⚠️ 关于OpenWRT版”京东多合一签到脚本“或其他任何下游脚本的相关说明

### ISSUE THREAD

**Issue by NobyDa** [NobyDa/Script#338]
近期由于某些原因，一些基于本项目二次开发的插件/脚本出现使用上的问题后，出现了一些与之无关的issues；
现特此声明：

1. [本项目](https://github.com/NobyDa/Script)仅维护[README](https://github.com/NobyDa/Script/blob/master/README.md)中标明的 "脚本" 或 "脚本注释内标明的兼容应用"；其他任何下游脚本/插件（例如：[OpenWRT版](https://github.com/jerrykuku/luci-app-jd-dailybonus)、基于原版的二次开发NodeJS版）都不在[本项目](https://github.com/NobyDa/Script)的维护范围。
2. 下游/二次开发脚本如出现任何使用上的问题，请直接寻找相关作者提issues。
3. 不再解答任何与本项目脚本无关的issues。

望各位知悉。

**Comment by ninet23** [comment]
OK
