### ISSUE TITLE
解决问题之后提个建议

### ISSUE THREAD

**Issue by dearlinen** [NobyDa/Script#339]
京东签到脚本终于更新为一个json串存所有cookie了，之前也觉得这样比较简洁
不过更新过后出现了个问题，一直提示  

  >  异常京东Cookie已过滤，pt_key=xxx;pt_pin=xxx

找了一会发现是更新后cookie匹配规则改变了，cookie字符串结束时也要加上`;`
这个在脚本注释里是没有加上的，建议添加一下，或者直接用`split`解析（显然下游又要考虑兼容了

**Comment by simonfxm** [comment]
cookies用手机扫码后获取不到，手机页面显示“请升级为最新版本”，但已经是最新版本了，一直停留在这个页面，脚本出现二维码后也一直没有变化

**Comment by NobyDa** [comment]
> 京东签到脚本终于更新为一个json串存所有cookie了，之前也觉得这样比较简洁
> 
> 不过更新过后出现了个问题，一直提示  
> 
> 
> 
>   >  异常京东Cookie已过滤，pt_key=xxx;pt_pin=xxx
> 
> 
> 
> 找了一会发现是更新后cookie匹配规则改变了，cookie字符串结束时也要加上`;`
> 
> 这个在脚本注释里是没有加上的，建议添加一下，或者直接用`split`解析（显然下游又要考虑兼容了

在脚本里的cookie样例中已明确需要;结尾，只是没有特别标明。。

**Comment by dearlinen** [comment]
> > 京东签到脚本终于更新为一个json串存所有cookie了，之前也觉得这样比较简洁
> > 不过更新过后出现了个问题，一直提示
> > > 异常京东Cookie已过滤，pt_key=xxx;pt_pin=xxx
> > 
> > 
> > 找了一会发现是更新后cookie匹配规则改变了，cookie字符串结束时也要加上`;`
> > 这个在脚本注释里是没有加上的，建议添加一下，或者直接用`split`解析（显然下游又要考虑兼容了
> 
> 在脚本里的cookie样例中已明确需要;结尾，只是没有特别标明。。

😂我一开始以为是别的问题，结果试了几种方法都没用，最后也没注意到cookie样例的区别，看了match规则才发现的。老哥还是加个注释吧，防止有人想我一样呆
