### ISSUE TITLE
哔哩哔哩漫画无法获取Cookie

### ISSUE THREAD

**Issue by ericedwars** [NobyDa/Script#340]
请问大佬，哔哩哔哩漫画获取Cookie时，提示“Cookie关键值缺失”该怎么处理？已经按照之前的issue修改正则匹配url也还是不行

**Comment by NobyDa** [comment]
> 请问大佬，哔哩哔哩漫画获取Cookie时，提示“Cookie关键值缺失”该怎么处理？已经按照之前的issue修改正则匹配url也还是不行

改成以下正则再试试：
```
^https:\/\/app\.bilibili\.com\/x\/v2\/account\/myinfo
```
如果配置内没有MITM以上主机名，则再加一条主机名即可.

**Comment by ericedwars** [comment]
谢谢大佬，可以用了
