### ISSUE TITLE
JD_DailyBonus.js运行时候流量异常,请问大佬是否正常?

### ISSUE THREAD

**Issue by zhanggaolei001** [NobyDa/Script#341]
上下流量会增加2~5MB左右

**Comment by NobyDa** [comment]
正常行为。上传50-100KB，下载会达到2-5MB左右；某些API返回的响应会比较大。

**Comment by zhanggaolei001** [comment]
不是下载这个文件时候2-5M,而是一直尺寸这样(我是早上发现的,可能持续运行了六个小时,号比较多),只要运行此脚本.
另外我的一些其他尝试:
单进程宠汪汪二代目脚本测试:<200K左右
XiaoHe的京东试用脚本,10个进程:≈200K左右.



***@***.***
 
发件人： NobyDa
发送时间： 2021-09-09 17:09
收件人： NobyDa/Script
抄送： zhanggaolei001; Author
主题： Re: [NobyDa/Script] JD_DailyBonus.js运行时候流量异常,请问大佬是否正常? (#341)
正常行为。上传50-100KB，下载会达到2-5MB左右；某些API返回的响应会比较大。
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by NobyDa** [comment]
不知道你想表达什么。前面已经描述过了，脚本运行时所触发的网络请求 单个账号所产生的网络流量会在2-5MB左右(下载)，其中上传50-100KB.
多个账号所产生的"持续带宽占用"没有试过，但不会低于2MB/s
