### ISSUE TITLE
B站换区脚本通知堆积

### ISSUE THREAD

**Issue by Little-Ming-1998** [NobyDa/Script#350]
设置B站换区脚本后，在观看B站时会出现同一策略切换到同一策略的情况，造成大量相同策略名的通知堆积，是否有办法在不关闭通知的情况下对重复通知进行精简

**Comment by NobyDa** [comment]
那是你策略名配置错误；脚本内已经注明QX用户填写策略名时注意大小写。

**Comment by Little-Ming-1998** [comment]
已经清除会话重设

**Comment by Little-Ming-1998** [comment]
> 那是你策略名配置错误；脚本内已经注明QX用户填写策略名时注意大小写。

![5AD93BFA-35C6-4593-8B07-0B3A29BB52F5](https://user-images.githubusercontent.com/41013339/140278669-4cbf8dfb-2a65-4f2e-aa5e-632551b3df94.png)
这样是正常情况吗？
