### ISSUE TITLE
爱奇艺签到失败

### ISSUE THREAD

**Issue by happyskey** [NobyDa/Script#351]
## 开始执行... 2021-11-09 08:46:03

爱奇艺-查询成功: 2023-04-06到期 
爱奇艺-签到失败: 今日已签到 ⚠️ 
爱奇艺-抽奖明细: 未中奖 🎉 (1) 

签到用时: 4.64 秒

## 执行结束... 2021-11-09 08:46:11 耗时 8 秒

实际到网站上查看还是失败的，cookie用的p0001

**Comment by IPlayForHer** [comment]
这个项目好像被放弃了，我前段时间优化了爱奇艺的脚本发了pr都没回复，我过两天有时间修一下修好我会发出来

**Comment by IPlayForHer** [comment]
噢我看了一下你发的issue这个脚本上个月还是能用的

**Comment by NobyDa** [comment]
> 这个项目好像被放弃了，我前段时间优化了爱奇艺的脚本发了pr都没回复，我过两天有时间修一下修好我会发出来

其中一行代码的问题20天前就回复过了呀
