### ISSUE TITLE
[APP内购]是否能增加 DAMA 的APP内购

### ISSUE THREAD

**Issue by FlechazoPh** [NobyDa/Script#360]
如图，内购后保存可去水印
![5EC1DF1C-D494-465F-8EAC-42D5E75C8965](https://user-images.githubusercontent.com/94276146/149058447-4d5ce1c5-7348-418e-9e78-7aca1d7e4bd1.png)

App Store 链接：
https://apps.apple.com/cn/app/dama-%E5%9B%BE%E7%89%87%E9%9A%90%E7%A7%81%E6%99%BA%E8%83%BD%E6%89%93%E7%A0%81/id1534690075

**Comment by NobyDa** [comment]
也不贵。良心app不多了，直接买呗。

**Comment by FlechazoPh** [comment]
> 也不贵。良心app不多了，直接买呗。

也行，支持一下~
