### ISSUE TITLE
哔哩自动区域切换在quantumult x环境下对1月新番失效

### ISSUE THREAD

**Issue by USBsky** [NobyDa/Script#363]
https://raw.githubusercontent.com/NobyDa/Script/master/Surge/JS/Bili_Auto_Regions.js

经过测试，只有一月新番存在无法切换的现象，之前的番剧切换正常。
此外，后缀加“港”，“台”的搜索方法也失效了，无法搜到番剧

**Comment by NobyDa** [comment]
更新脚本/BoxJs订阅，填写后备子策略。

Yang Junran ***@***.***>于2022年1月22日 周六20:32写道：
