### ISSUE TITLE
豌豆荚下载被拦截 alissl.ucdl.pp.uc.cn

### ISSUE THREAD

**Issue by Azureki** [NobyDa/Script#365]
AdRule 中的 `DOMAIN-SUFFIX,alissl.ucdl.pp.uc.cn`  这条规则拦截了豌豆荚的下载链接。
我是用安卓的，也许确实有很多广告是这个域名？

**Comment by NobyDa** [comment]
将在下个commit中移除。该私有规则集极少维护，建议更换其他作者的规则。
