### ISSUE TITLE
爱奇艺的观看视频任务是要自己看吗？

### ISSUE THREAD

**Issue by lxr760** [NobyDa/Script#372]
脚本运行后提示如下：
爱奇艺-任务列表: 获取成功! 
爱奇艺-领取任务: 观看视频30分钟 => A00000 
爱奇艺-开始任务: 观看视频30分钟 => A00000 
爱奇艺-任务奖励: 观看视频30分钟 => 未完成 ⚠️

**Comment by NobyDa** [comment]
预期行为。没看30分钟视频怎么完成。。

**Comment by lxr760** [comment]
> 预期行为。没看30分钟视频怎么完成。。

这个脚本能自动完成观看30min吗

**Comment by NobyDa** [comment]
> > 预期行为。没看30分钟视频怎么完成。。
> 
> 
> 
> 这个脚本能自动完成观看30min吗 

没具体调过；这个奖励好像是积分，没什么太大意义。。
