### ISSUE TITLE
vsco会员是不是失效了？

### ISSUE THREAD

**Issue by huge67** [NobyDa/Script#378]
iPhone + Quantumult X

**Comment by NobyDa** [comment]
测试正常.

**Comment by huge67** [comment]
大佬，我测试vsco脚本，出现这个错误。
![image](https://user-images.githubusercontent.com/47515842/157407741-4e99a8ab-97db-4b42-a145-fffe46455811.png)

**Comment by NobyDa** [comment]
重写类型脚本不是让你手动运行的。

**Comment by huge67** [comment]
问题解决，退出并重新登录VSCO
