### ISSUE TITLE
关于bili换区脚本首页动画显示地区的问题

### ISSUE THREAD

**Issue by pipixia244** [NobyDa/Script#383]
使用脚本后，番剧观看均正常，但刚打开b站后点击动画页面却会在两种界面中横跳，有的时候是大陆版的有的时候是港台版的，如下两图。
请问如果我想把这个界面固定在港台区的界面该怎么做呢？谢谢～
![E19A3E01-B2CC-49C7-A731-E69697C83552](https://user-images.githubusercontent.com/56287117/161333480-6459f04c-7213-4e87-b5b7-ee922f7e2d4f.png)
![A001D3C2-7791-4D0A-8022-AF738DBBB457](https://user-images.githubusercontent.com/56287117/161333497-949932bd-09db-4462-b342-1c7e10131f17.png)

**Comment by NobyDa** [comment]
可通过另一个脚本解决，具体效果为：可显示两种标签页

以下为surge配置，其他app需自行更改格式
```Bili-Tab = type=http-response,pattern=^https?:\/\/app\.bilibili\.com\/x\/resource\/show\/tab,requires-body=1,max-size=0,script-path=https://gist.githubusercontent.com/NobyDa/60ef3eecba473185d01d0c6ca6c30326/raw/BiliBili_Tab.js```

**Comment by pipixia244** [comment]
使用该脚本成功解决，感谢回复！

**Comment by Fannncy** [comment]
让新春的风吹进你的屋子让新春的雪飞进你的屋子让我新春的祝愿                      飘进你的心坎新春贺喜
