### ISSUE TITLE
关于B站自动换区脚本的一点建议

### ISSUE THREAD

**Issue by zkyary** [NobyDa/Script#395]
观看港澳台番剧后，B站连着外网，有时看完后会直接退出APP。而下次启动时，默认还是走的代理，不会切到直连模式。能否把启动时默认开启直连模式加入到脚本中？目前有个其他作者的能实现该功能的补充脚本：
^https?:\/\/api\.bilibili\.com\/x\/offline\/version url script-response-body https://raw.githubusercontent.com/ddgksf2013/Cuttlefish/master/Script/bilibili_startup_direct.js
但是该脚本应该只适用于QX，在Surge上无效。所以希望大佬能够将其补充进换区脚本，如果可以配合Boxjs让使用者自己选择启动时默认走直连还是代理那样应该更好

**Comment by NobyDa** [comment]
理论上无需修改脚本，直接可支持该需求：
`[Script]`
`bili启动直连 = type=http-response,pattern=^https?:\/\/api\.bilibili\.com\/x\/offline\/version,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/NobyDa/Script/master/Surge/JS/Bili_Auto_Regions.js`

**Comment by zkyary** [comment]
> 理论上无需修改脚本，直接可支持该需求：
> 
> `[Script]`
> 
> `bili启动直连 = type=http-response,pattern=^https?:\/\/api\.bilibili\.com\/x\/offline\/version,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/NobyDa/Script/master/Surge/JS/Bili_Auto_Regions.js`
> 
> 

试了下，确实可行👍🏻👍🏻👍🏻
