### ISSUE TITLE
Script/QuantumultX/Js.conf中的VSCO VIP相关匹配会导致其他APP正常的会员鉴权失效

### ISSUE THREAD

**Issue by TsXcd** [NobyDa/Script#396]
该配置中的VSCO相关匹配项会导致 我Aphrodite的正常付费会员认证失败，不知是否可以更为精准的匹配防止误伤？

~~并且我尝试使用VSCO后 在会员的相关权益页并未获得实际会员作用  不知是否可将其先屏蔽？~~

**Comment by NobyDa** [comment]
请更新脚本后再次尝试一下。

**Comment by TsXcd** [comment]
> 请更新脚本后再次尝试一下。

更新后问题无复现，感谢。
