### ISSUE TITLE
希望 Loon 插件后缀名能统一命名为 .plugin

### ISSUE THREAD

**Issue by Peng-YM** [NobyDa/Script#398]
大佬，Loon 插件仓库是根据文件后缀名判断是否是 Loon 插件。由于目前本仓库的插件是以 .Conf 结尾，因此无法自动收录本仓库的插件。能否请大佬改一下名字呢？

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by NobyDa** [comment]
> 大佬，Loon 插件仓库是根据文件后缀名判断是否是 Loon 插件。由于目前本仓库的插件是以 .Conf 结尾，因此无法自动收录本仓库的插件。能否请大佬改一下名字呢？
> 
> <sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

晚点处理一下，不过可能会造成用户404困扰

**Comment by Peng-YM** [comment]
可以让3K在频道说明一下~
