### ISSUE TITLE
每次接受都会弹出无法接入 App Store Connect ！

### ISSUE THREAD

**Issue by Semporia** [NobyDa/Script#403]
每次都会弹出，点击“好”之后再次点击接受才会正常！
![IMAGE 2022-06-23 10:39:06](https://user-images.githubusercontent.com/29939899/175195417-3e4fbdd8-b81b-43c5-85b5-867d48d2f4d9.jpg)

**Comment by NobyDa** [comment]
描述下具体的复现步骤、app、系统版本，以及app日志是否有报错
