### ISSUE TITLE
fileball更新到最新的1.1.48版本 qx解锁失效

### ISSUE THREAD

**Issue by zhutou3** [NobyDa/Script#408]
不知道大佬能否修复，感谢！如果无法修复的话就自行降级到最后支持版本1.1.47。

**Comment by NobyDa** [comment]
由于一些原因，新版脚本已移除对该app的支持。如需继续使用请自行降级以及更换[旧脚本链接](https://raw.githubusercontent.com/NobyDa/Script/f489cbbb2ff516543d54b865b53c0afdb293d6a9/QuantumultX/File/vsco.js)
