### ISSUE TITLE
Adrule.list里有条规则会导致今日头条搜索不能用

### ISSUE THREAD

**Issue by zjcfynn** [NobyDa/Script#41]
DOMAIN-SUFFIX,is.snssdk.com
就是这条，删除应该就行。我暂时的解决方式是加了一条direct
用的是surgeTF版本

**Comment by MasterCh1ef** [comment]
我这里如果对*.snsssdk.com进行解密，会直接导致surge不能使用，而quanX则无此问题……

**Comment by zjcfynn** [comment]
只是删掉DOMAIN-SUFFIX,is.snssdk.com这条呢？因为我看您的Adrule.list规则中关于snsssdk.com相关的其实是分别写出来了的，而不是写成*.snsssdk.com的格式

**Comment by NobyDa** [comment]
Thank
