### ISSUE TITLE
TestFlightAccount反馈

### ISSUE THREAD

**Issue by RuCu6** [NobyDa/Script#410]
使用脚本会导致 无法安装 的问题

使用原来的 TestFlightDownload.conf 可以正常安装  不知道触发了苹果的什么限制

如下图

![809DDC61-ED5C-4032-8FB7-39EA2D2E5B8D](https://user-images.githubusercontent.com/49463634/179132900-e48f3610-fece-40e9-a152-06843eee33d9.png)

**Comment by NobyDa** [comment]
不存在该问题。自行检查脚本是否为最新版。

**Comment by RuCu6** [comment]
更新新版后已解决  很抱歉打扰了
