### ISSUE TITLE
哔哩哔哩自动换区和搜索换区脚本失效

### ISSUE THREAD

**Issue by LimeAroma** [NobyDa/Script#415]
1、现在退出搜索框返回首页并不会切回直连了
2、在搜索港台番剧后，必须要在番剧名后加上“中”才切换回直连，之前是不需要的

**Comment by NobyDa** [comment]
关于第一点：由于一些冲突以及可能会造成误判，现在仅“冷启动”哔哩APP时会切回DIRECT。
关于第二点：自行修改Bili搜索脚本的匹配URL正则为：
```
^https:\/\/ap(p|i)\.bili(bili|api)\.(com|net)\/x\/v2\/search(\/type|)\?
```
