### ISSUE TITLE
微博开屏广告有时会失效

### ISSUE THREAD

**Issue by wongdean** [NobyDa/Script#42]
开发者你好，我挂在本地 js 脚本，微博开屏广告这几天好像又失效了。我查看 quan x 的任务详情，好像是脚本问题(但不清楚是不是我自己的问题，如您测试无问题请关闭此 issue)
版本：quan x 1.0.4
iOS: 12.4.1
微博：最新版

https://github.com/yichahucha/surge/tree/master

这个脚本好像更新了？

**Comment by NobyDa** [comment]
我这边不用脚本也没出现启屏广告 你可以尝试添加我自用的规则以及Rewrite
[AdRule.list](https://raw.githubusercontent.com/NobyDa/Script/master/QuantumultX/AdRule.list)
[AdRuleTest.list](https://raw.githubusercontent.com/NobyDa/Script/master/QuantumultX/AdRuleTest.list)
[Rewrite_lhie1.conf](https://raw.githubusercontent.com/NobyDa/Script/master/QuantumultX/Rewrite_lhie1.conf)

简介:
https://github.com/NobyDa/Script/tree/master/QuantumultX

**Comment by wongdean** [comment]
好的，已经安排了，谢谢您！
