### ISSUE TITLE
关于WeChat规则是否可以修改

### ISSUE THREAD

**Issue by futurkk** [NobyDa/Script#421]
您好，想问一下WeChat规则中比如
`DOMAIN-KEYWORD,101.226.211.`
我是否可以修改为
`IP-CIDR,101.226.211.0/24`
这种写法，是否WeChat请求特殊，所以才需要关键词子规则呢？

**Comment by NobyDa** [comment]
由于微信使用双栈网络，且观察到微信在IPv6网络环境良好的情况下会优先使用IPv6，不可避免的会进行IPv4 to IPv6的访问转换，进而出现以IPv4映射的IPv6地址(例如::ffff:101.226.211.0)，该类映射地址如果使用CIDR规则会非常繁琐且数量过多，故而以关键词类型规则代替。简而言之，如果不使用IPv6，则可以自行修改为CIDR规则。

另：该规则集纯自用，因去年为实现某些特殊需求而存在；现由于需求变动已暂停更新，所以目前的规则可能并不严谨和准确。

**Comment by futurkk** [comment]
麻烦啦，感谢您的解答！
