### ISSUE TITLE
bilibili 自动换区搜索不到港台区资源问题

### ISSUE THREAD

**Issue by m174460635** [NobyDa/Script#422]
b站自动换区没有问题，但是搜索不好使，求助一下！![image](https://user-images.githubusercontent.com/20900457/188255881-a7413ded-25c1-4234-94da-e4cf970457d6.png)

**Comment by NobyDa** [comment]
检查脚本配置以及相关网络请求是否命中脚本。

**Comment by m174460635** [comment]
> 检查脚本配置以及相关网络请求是否命中脚本。

网络请求走的对应的b站策略，但是搜索没有命中脚本，不知道什么原因。如图
![image](https://user-images.githubusercontent.com/20900457/188356029-73e150dc-062a-475f-87a9-aa39476a517d.png)
![image](https://user-images.githubusercontent.com/20900457/188356085-8ac52eda-80e3-405f-a1a5-03726399e734.png)
只有自动换区脚本命中了。搜索没有，就很迷惑。

**Comment by NobyDa** [comment]
确实有问题，似乎哔哩哔哩中国区app的搜索api升级成grpc请求了，目前脚本无法处理。

另：目前外区哔哩哔哩app（白图标）暂时没有这个问题。

**Comment by m174460635** [comment]
多谢啦，我试试外区的app
