### ISSUE TITLE
希望增加b站番剧换区10s后自动切回直连的选项

### ISSUE THREAD

**Issue by ASIjacket** [NobyDa/Script#425]
番剧加载后，一般分配国外的akaized cdn 和 国内ip的mcdn，前者可以rewtite到国内cdn，

但是由于规则的限制所有b站流量都会被代理，

所以可以加一个开关，自动切回直连节约流量。~~为什么10s？为了平滑加载过度~~

当然也可以手动把B站所有cdn设为直连，不过不是很优雅，佬觉得呢？

**Comment by im-Kalix** [comment]
B站分流规则只要下面两条就够了
｀DOMAIN,api.bilibili.com,哔哩哔哩 // 哔哩哔哩API（包含地区检测）
DOMAIN,grpc.biliapi.net,哔哩哔哩 // 哔哩哔哩gRPC（包含地区检测）｀
其他流量可以用全局配置。

我现在想的是能不能加一个功能，在观看普通视频的时候自动切回DIRECT策略。

**Comment by guokongming** [comment]
Thank you very much for your reply. Your email has been received.Have a nice day and give my best wishes to you.
