### ISSUE TITLE
TestFlight账户管理脚本在小火箭2.2.19之后版本问题

### ISSUE THREAD

**Issue by chengkongyiban** [NobyDa/Script#427]
在小火箭2.2.19及2.2.20版本使用该脚本，可合并TF账号，但安装或更新都会提示"TF目前不可用，请稍后再试"。

**Comment by NobyDa** [comment]
该问题需要等待Shadowrocket开发者修正，可自行邮件反馈：
Known bug: JSON.stringify($request) causes $request.body to disappear (non binary)

**Comment by chengkongyiban** [comment]
谢谢大佬，最新shadowrocket测试版中已修复该bug。

**Comment by chengkongyiban** [comment]
您好，在shadowrocket新的测试版2.2.22（1814）中，该脚本的解除区域限制功能不生效。回退2.2.18（1756）测试同样不生效。由于不会抓日志，麻烦您帮忙看下问题出在哪里，谢谢。

**Comment by chengkongyiban** [comment]
作者在2.2.22 （1815）版本已修复该问题
