### ISSUE TITLE
开启http2后搜索不出港台番剧

### ISSUE THREAD

**Issue by LimeAroma** [NobyDa/Script#440]
查看策略组切换到香港成功，脚本也触发了但还是无法看到港台番剧的搜索结果。关闭http2则一切正常

**Comment by LimeAroma** [comment]
> 使用bilibili白图标外区版

一直用的白色哔哩哔哩，代理工具是loon。手头上没有其他工具测试

**Comment by NobyDa** [comment]
> > 使用bilibili白图标外区版
> 
> 
> 
> 一直用的白色哔哩哔哩，代理工具是loon。手头上没有其他工具测试

刚试了一下，粗略估计是Loon H2模式的bug：
请求被http-request劫持时，切换策略没有及时打断请求，导致请求被原策略复用。

可自行邮件咨询Loon开发者。
