### ISSUE TITLE
wechat.js mitm 里面是否应该加入%APPEND%

### ISSUE THREAD

**Issue by AmiasWayne** [NobyDa/Script#443]
大佬请帮忙检查下。感谢。

**Comment by NobyDa** [comment]
没看太懂这个issues，`%APPEND%`这个关键字是Surge模块所使用的，`wechat.js`这个脚本里注释的配置是让你直接加进配置文件的，本身就不是Surge模块格式。

**Comment by AmiasWayne** [comment]
> 没看太懂这个issues，`%APPEND%`这个关键字是Surge模块所使用的，`wechat.js`这个脚本里注释的配置是让你直接加进配置文件的，本身就不是Surge模块格式。

**Comment by AmiasWayne** [comment]
> 没看太懂这个issues，`%APPEND%`这个关键字是Surge模块所使用的，`wechat.js`这个脚本里注释的配置是让你直接加进配置文件的，本身就不是Surge模块格式。

明白 感谢大佬 我昨天复制粘贴里面的内容加了一个本地模块 发现其他模块的mitm失效了 所以问了一下😂😂
