### ISSUE TITLE
AdRule规则误杀摸鱼kik

### ISSUE THREAD

**Issue by junetwentytwo** [NobyDa/Script#444]
这是一款搜狐出品的App，有些规则会导致视频无法播放，可以排查一下。例如以下这条：

https://h5-ol.sns.sohu.com/hy-moyukik-h5/share/feed/1645401995743359009?sf_my=copylink&cid=026796255891793921280&uid=1066326

**Comment by junetwentytwo** [comment]
发现QuantumultX下的子文件夹名Sinppet写反了😂

**Comment by NobyDa** [comment]
> 发现QuantumultX下的子文件夹名Sinppet写反了😂

这就尴尬了😅

**Comment by junetwentytwo** [comment]
> > 发现QuantumultX下的子文件夹名Sinppet写反了😂
> 
> 这就尴尬了😅

第一个导致视频无法加载的规则也找到了，是data.vod.itc.cn这条，大佬这两条规则什么时候可以修正一下哈
