### ISSUE TITLE
TestFlight账户管理脚本失效了

### ISSUE THREAD

**Issue by orangesaig** [NobyDa/Script#445]
![IMG_2557](https://user-images.githubusercontent.com/65300604/231614088-89c794d0-9e64-402f-8a8b-6cac119b9230.jpeg)
之前好好的，这两天的tf都更新不了。要关掉脚本，手动切换账号才能更新。iOS16.4.1，13pro，qx 。

**Comment by NobyDa** [comment]
暂未接到其他类似反馈
