### ISSUE TITLE
如何获取JDCOOKIE？

### ISSUE THREAD

**Issue by Marblog** [NobyDa/Script#446]
目前环境是Shadowrocket，一键安装，`如果你使用的是 v2.2.8 (1658) 及以上的版本，你可以直接: [一键安装](http://api.boxjs.app/shadowrocket-install)`

看了注释导入了脚本注释，访问Safari浏览器打开登录 https://home.m.jd.com/myJd/newhome.action 点击"我的"页面   没有获取到cookie，有相关的文档吗，要怎么操作的

**Comment by NobyDa** [comment]
仓库内的京东脚本两年前就已停止维护，目前是完全失效的状态。
