### ISSUE TITLE
白图标B站，换区失败，之前没问题的，现在版本是3.18.0

### ISSUE THREAD

**Issue by Anivia2015** [NobyDa/Script#458]

**Comment by Anivia2015** [comment]
![7B274FDC829C3CCBDDA9BD0AA8A49D59](https://github.com/NobyDa/Script/assets/68541890/58accf2d-90e4-4b84-b45c-bcb684cd5c53)
![3F7727EA0180810ABB0AB76C9B686316](https://github.com/NobyDa/Script/assets/68541890/589e682b-c18a-4dbe-b95d-020a516f196e)
![17F6370329F8EF520125F9AD4432F26C](https://github.com/NobyDa/Script/assets/68541890/19c6208b-113d-4e79-b010-d3c62eb0fb22)

**Comment by NobyDa** [comment]
白b的搜索接口升级成grpc请求了，因为有其他项目写了类似的脚本，暂时不重复造轮子了。

相关项目：https://github.com/BiliUniverse/Universe/wiki/%F0%9F%8C%90-Global

**Comment by Anivia2015** [comment]
> 白b的搜索接口升级成grpc请求了，因为有其他项目写了类似的脚本，暂时不重复造轮子了。
> 
> 相关项目：https://github.com/BiliUniverse/Universe/wiki/%F0%9F%8C%90-Global

感谢大佬
