### ISSUE TITLE
粗心！！！！这个文件错误了

### ISSUE THREAD

**Issue by GodFreedom** [NobyDa/Script#476]
https://raw.githubusercontent.com/NobyDa/ND-AD/master/Surge/AD_Block_Plus.txt 这个地址，第一行开头的f，这么粗心！！

![CleanShot 2024-04-28 at 15 58 50@2x](https://github.com/NobyDa/Script/assets/50287531/af266cd5-75f9-4d42-ad19-2ec33b2af789)

**Comment by NobyDa** [comment]
哈哈，这个规则集已经不维护啦

**Comment by GodFreedom** [comment]
> 哈哈，这个规则集已经不维护啦

没法去掉吗？已经改不了了？

**Comment by NobyDa** [comment]
> > 哈哈，这个规则集已经不维护啦
> 
> 
> 
> 没法去掉吗？已经改不了了？

已改。现在这规则集还好用么

**Comment by GodFreedom** [comment]
> > > 哈哈，这个规则集已经不维护啦
> > 
> > 
> > 没法去掉吗？已经改不了了？
> 
> 已改。现在这规则集还好用么

当然好用啊

**Comment by GodFreedom** [comment]
> 哈哈，这个规则集已经不维护啦

老板，你现在用哪个去广告的list啊
