### ISSUE TITLE
wechat.js

### ISSUE THREAD

**Issue by spacexnasa** [NobyDa/Script#479]
你好，大佬 Wechat.js 这个文件好像失效了，但是我不知道怎么修改，  /getappmsgad  没有这个了   只看到 /mp/jsmonitor

**Comment by spacexnasa** [comment]
有的，有的中间也会夹杂广告的
https://mp.weixin.qq.com/s/uQ80PJAxPtgGtY98LmAubQ  比如这个

**Comment by NobyDa** [comment]
可能你没有用去广告规则，把这个域名`wxa.wxs.qq.com`REJECT就行

**Comment by spacexnasa** [comment]
> wxa.wxs.qq.com

这个加了， 用的小火箭的这个模块   https://whatshub.top/module/wechatad.module,然后我看  https?:\/\/mp\.weixin\.qq\.com\/mp\/getappmsgad，是这个，但是小火箭没有看到请求这个 getappmsgad

**Comment by spacexnasa** [comment]
我现在给这个也加到了 reject   badjs.weixinbridge.com，感觉稍微好点

**Comment by spacexnasa** [comment]
> 我也没见着那条正则能匹配，脚本一般都有时效性，应该是失效了。
> 
> 实测Surge加上 `DOMAIN,wxa.wxs.qq.com,REJECT, extended-matching` 就没见着广告了。文章作者自己加的广告倒是还有，还是凑合用规则吧。。


哎，好吧，我看火箭只有   DOMAIN,wxa.wxs.qq.com,REJECT
