### ISSUE TITLE
Js_local_WorkingCopy_New.conf 拆分

### ISSUE THREAD

**Issue by maxduke** [NobyDa/Script#58]
Js_local_WorkingCopy_New.conf 中既有一般的JS规则也有专门获取cookie的规则，建议能把cookie获取的拆分出来，这样能在已经获取到签到cookie的情况下，可以关闭相应的规则，主要考虑到获取cookie的一些host “*.iqiyi.com, www.52pojie.cn, c.tieba.baidu.com, api.m.jd.com, manga.bilibili.com,”波及比较广，平时正常浏览的情况下也会mitm，可能会影响效率，而且跑task的时候也是不需要这些host的

**Comment by NobyDa** [comment]
good idea
