### ISSUE TITLE
Rewrite_lhie1.conf里知乎规则

### ISSUE THREAD

**Issue by Wangsc1** [NobyDa/Script#62]
^https?:\/\/pic\d\.zhimg\.com\/v2.+ url reject-img
hostname: pic2.zhimg.com这条规则会导致知乎推荐里面视频预览图片消失

![09AA3194-407E-4C2D-9C8C-F4AA8B2656AB](https://user-images.githubusercontent.com/26079238/73150373-000f5900-4101-11ea-87e7-ceb49c22e2dc.jpeg)

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by NobyDa** [comment]
> 
> ^https?:\/\/pic\d\.zhimg\.com\/v2.+ url reject-img
> hostname: pic2.zhimg.com这条规则会导致知乎推荐里面视频预览图片消失
> 
> ![09AA3194-407E-4C2D-9C8C-F4AA8B2656AB](https://user-images.githubusercontent.com/26079238/73150373-000f5900-4101-11ea-87e7-ceb49c22e2dc.jpeg)
> 
> <sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

我这似乎没问题.

**Comment by Wangsc1** [comment]
empty_sni_enabled = true这个你开了吗

**Comment by NobyDa** [comment]
> empty_sni_enabled = true这个你开了吗


未开, 这个字段如果你不了解, 请务必false.

**Comment by Wangsc1** [comment]
> > empty_sni_enabled = true这个你开了吗
> 
> 未开, 这个字段如果你不了解, 请务必false.

不开的话屏蔽不了知乎广告，开了就会那样，其他好像也没什么影响
