### ISSUE TITLE
请问quantumult x1.05的rewrite_remote远程脚本到底能不能用啊？

### ISSUE THREAD

**Issue by donething** [NobyDa/Script#69]
我引用 https://raw.githubusercontent.com/NobyDa/Script/master/QuantumultX/Js.conf 的脚本后，抖音确实可以免除水印保存视频。
但我自己写的配置和脚本脚本上传到GitHub后，点击配置的"Raw"得到实际链接 https://raw.githubusercontent.com/donething/rewrite_js/master/qx/rewrite.conf ，引用后却不生效，日志中提示"null script"。
我真的被弄迷糊了，到底怎么回事啊。求解答。。。

**Comment by vsug** [comment]
早就不支持远程引用了，要么下载放进文件`我的iPhone/quantumultx/scrip`里面，要么打开iCloud，放在类似路径

**Comment by donething** [comment]
> 早就不支持远程引用了，要么下载放进文件`我的iPhone/quantumultx/scrip`里面，要么打开iCloud，放在类似路径

但是我试过开关qx，打开qx时抖音下载的视频无水印，关闭后会有水印。这应该是远程脚本的作用啊，我现在很迷糊。。

**Comment by vsug** [comment]
> > 早就不支持远程引用了，要么下载放进文件`我的iPhone/quantumultx/scrip`里面，要么打开iCloud，放在类似路径
> 
> 但是我试过开关qx，打开qx时抖音下载的视频无水印，关闭后会有水印。这应该是远程脚本的作用啊，我现在很迷糊。。

你看你路径里面有没有。我没用过支持远程脚本的版本，所以不知道哪个版本是不是自动将远程脚本下载到对应路径还是保存到本机不能看到，不管怎么样现在远程引用已经砍掉了，你想使用更新的脚本就手动处理，下载加上改一下配置文件用文件名调用。

**Comment by donething** [comment]
> > > 早就不支持远程引用了，要么下载放进文件`我的iPhone/quantumultx/scrip`里面，要么打开iCloud，放在类似路径
> > 
> > 
> > 但是我试过开关qx，打开qx时抖音下载的视频无水印，关闭后会有水印。这应该是远程脚本的作用啊，我现在很迷糊。。
> 
> 你看你路径里面有没有。我没用过支持远程脚本的版本，所以不知道哪个版本是不是自动将远程脚本下载到对应路径还是保存到本机不能看到，不管怎么样现在远程引用已经砍掉了，你想使用更新的脚本就手动处理，下载加上改一下配置文件用文件名调用。

好吧，谢谢

**Comment by vsug** [comment]
好吧是什么意思……我问你路径里面有没有，文件应用里面看一下。

**Comment by donething** [comment]
> 好吧是什么意思……我问你路径里面有没有，文件应用里面看一下。

iPhone/quantumultx/scrip里的是空的，我感觉要发邮件问下qx的开发者。。

**Comment by vsug** [comment]
所以你到底有没有认真看我写了什么……
我叫你把新的脚本放进去，在配置里面使用文件名调用，你去问开发者他也是这么回答你。

**Comment by vsug** [comment]
至于配置具体怎么改，参见https://www.notion.so/kopshawn/Quantumult-X-1d32ddc6e61c4892ad2ec5ea47f00917
好好研究

**Comment by vsug** [comment]
远程脚本引用的功能已经砍掉了，你无论怎么改都没用，只能把脚本下载下来放进本地，听懂了没。

**Comment by donething** [comment]
> 所以你到底有没有认真看我写了什么……
> 我叫你把新的脚本放进去，在配置里面使用文件名调用，你去问开发者他也是这么回答你。

我问的是标题那个问题，而不是怎么将远程脚本本地化使用的问题，我知道怎么本地化。

**Comment by NobyDa** [comment]
Q: 引用 https://raw.githubusercontent.com/NobyDa/Script/master/QuantumultX/Js.conf 的脚本后，抖音确实可以免除水印保存视频。
A: 请先理解rewrite的 url307和url script-response-body字段, 后者的字段在QX最新商店版中, 只可引用本地路径脚本, 意味着已经去除了远程脚本url的引用

Q: 自己写的配置和脚本脚本上传到GitHub后，点击配置的"Raw"得到实际链接 https://raw.githubusercontent.com/donething/rewrite_js/master/qx/rewrite.conf ，引用后却不生效，日志中提示"null script"。
A: 请先理解本地引用订阅与远程引用订阅的区别, 远程里写的本地路径, 如本地路径无脚本, 不提示null script那提示什么?

**Comment by donething** [comment]
> Q: 引用 https://raw.githubusercontent.com/NobyDa/Script/master/QuantumultX/Js.conf 的脚本后，抖音确实可以免除水印保存视频。
> A: 请先理解rewrite的 url307和url script-response-body字段, 后者的字段在QX最新商店版中, 只可引用本地路径脚本, 意味着已经去除了远程脚本url的引用
> 
> Q: 自己写的配置和脚本脚本上传到GitHub后，点击配置的"Raw"得到实际链接 https://raw.githubusercontent.com/donething/rewrite_js/master/qx/rewrite.conf ，引用后却不生效，日志中提示"null script"。
> A: 请先理解本地引用订阅与远程引用订阅的区别, 远程里写的本地路径, 如本地路径无脚本, 不提示null script那提示什么?

我不是想杠啊，请理解
A1：我看的是，抖音307是取消外区限制，去水印那个也是script-response-body那个。

**Comment by NobyDa** [comment]
(.*video_id=\w{32})(.*watermark=)(.*) url 302 $1
这条不是去水印是什么???

**Comment by donething** [comment]
> (.*video_id=\w{32})(._watermark=)(._) url 302 $1
> 这条不是去水印是什么???

我的错，明白了，谢谢你。
