### ISSUE TITLE
AdRuleRegex.list会导致网易云解锁播放失败

### ISSUE THREAD

**Issue by Liquor030** [NobyDa/Script#73]
通过代理进行解锁网易云灰色音乐。播放加载不出来。貌似被误杀

**Comment by Liquor030** [comment]
添加后正常
[MITM]
hostname = music.163.com,*.music.163.com

**Comment by jzx0001** [comment]
> 添加后正常
> 
> [MITM]
> 
> hostname = music.163.com,*.music.163.com

> 可是这两条添加了还是不行啊

**Comment by Liquor030** [comment]
> > 添加后正常
> > [MITM]
> > hostname = music.163.com,*.music.163.com
> 
> > 可是这两条添加了还是不行啊

不是添加这两条。
你可以在代理规则中最前面添加`DOMAIN,api.iplay.163.com,你的网易云策略组`试试
