### ISSUE TITLE
Douyin 水印失效

### ISSUE THREAD

**Issue by androidcn** [NobyDa/Script#74]
Douyin 水印失效

**Comment by NobyDa** [comment]
可以试试这位大佬的脚本, 对接一下qx格式即可.
https://github.com/Choler/Surge/blob/master/Script/Aweme.js

**Comment by androidcn** [comment]
直接替换JS
^https:\/\/.*\.amemv\.com\/aweme\/v.*\/(feed|post)/ url script-request-header NobyDa/Surge/JS/Aweme.js
^https:\/\/.*\.amemv\.com\/aweme\/v.*\/(feed|post)/ url script-response-body NobyDa/Surge/JS/Aweme.js

不成功

**Comment by NobyDa** [comment]
建议等Choler更新
