### ISSUE TITLE
AdRuleRegex.list中  URL-REGEX,^https?:\/\/.+\.snssdk\.com\/api\/ad\/  会引起某些异常

### ISSUE THREAD

**Issue by Liquor030** [NobyDa/Script#76]
例如：新下载的皮皮虾无法加载评论

解决：建议去除这条规则，采用脚本去除广告

我自己写了个脚本，有点简陋。。

```
http-response ^https?:\/\/.+\.snssdk\.com\/api\/ad\/ script-path= https://raw.githubusercontent.com/Liquor030/Sub_Ruleset/master/Script/snssdk.js,requires-body=true
```

**Comment by NobyDa** [comment]
可能不是这条规则引起的, 这边测试没有问题. 并且这条神机里也有的.

**Comment by Liquor030** [comment]
的确，我正在找原因，好像是因为返回的cell_id错误的原因

**Comment by Liquor030** [comment]
@NobyDa 找到问题所在了，如果没错的话，应该是JSON.parse 导致大数精度丢失。
cell_id=6799775096517957902 ===>> cell_id=6799775096517958000
真坑。。。。。。。

**Comment by Liquor030** [comment]
@NobyDa 修好了。。这个是真的坑人。。

```
http-response ^https?://.*\.snssdk\.com/bds/feed/stream/ requires-body=1,max-size=-1,script-path=https://raw.githubusercontent.com/Liquor030/Sub_Ruleset/master/Script/Super.js
```

**Comment by NobyDa** [comment]
哈哈, 这脚本去广告还有效果吗

**Comment by Liquor030** [comment]
修好了呀，就用我发那个就可以去广告了呀

http-response ^https?://.*\.snssdk\.com/bds/feed/stream/ requires-body=1,max-size=-1,script-path=https://raw.githubusercontent.com/Liquor030/Sub_Ruleset/master/Script/Super.js

**Comment by mtgq** [comment]
> 修好了呀，就用我发那个就可以去广告了呀
> 
> http-response ^https?://.*.snssdk.com/bds/feed/stream/ requires-body=1,max-size=-1,script-path=https://raw.githubusercontent.com/Liquor030/Sub_Ruleset/master/Script/Super.js

大佬，皮皮虾去广告是不是失效了呀？好像不起作用啦

**Comment by Liquor030** [comment]
> > 修好了呀，就用我发那个就可以去广告了呀
> 
> > 
> 
> > http-response ^https?://.*.snssdk.com/bds/feed/stream/ requires-body=1,max-size=-1,script-path=https://raw.githubusercontent.com/Liquor030/Sub_Ruleset/master/Script/Super.js
> 
> 
> 
> 大佬，皮皮虾去广告是不是失效了呀？好像不起作用啦

https://raw.githubusercontent.com/Liquor030/Sub_Ruleset/master/Module/Super_Ad.sgmodule
