### ISSUE TITLE
jdprice QuanX可否远程调用Task

### ISSUE THREAD

**Issue by androidcn** [NobyDa/Script#79]
jdprice QuanX可否远程调用Task
surge是可以的
quanX貌似只能本地

**Comment by YaoXiaoH** [comment]
> jdprice QuanX可否远程调用任务喘息
> 是可以的
> quanX貌似只能本地

quanX 貌似TF版可以，商店版要运行81天才能解锁远程，可以试试用workingcopy挂载仓库到本地，随时fetch就行。

**Comment by androidcn** [comment]
> > jdprice QuanX可否远程调用任务喘息
> > 是可以的
> > quanX貌似只能本地
> 
> quanX 貌似TF版可以，商店版要运行90天才能解锁远程，可以试试用workingcopy挂载仓库到本地，随时fetch就行。

一直在 macOS Github Desktop同步

**Comment by NobyDa** [comment]
目前QX TF可远程调用, 但该版本不会上架appstore
