### ISSUE TITLE
Quantumult X 报错

### ISSUE THREAD

**Issue by Furthermorer** [NobyDa/Script#8]
是用订阅脚本的
![40E83D8D-5475-4B1D-AF67-A0C130B8814B](https://user-images.githubusercontent.com/39948247/66890232-f4979680-f017-11e9-81a2-5c8848430915.png)

**Comment by NobyDa** [comment]
试一试最新QX订阅会不会报错, 因为所有脚本都是基于手机端写的 ipad不保证兼容性

**Comment by Furthermorer** [comment]
最新版没报错了，感谢
