### ISSUE TITLE
AdRuleRegex.list 知乎误杀

### ISSUE THREAD

**Issue by Liquor030** [NobyDa/Script#83]
AND,((USER-AGENT,osee2*), (NOT,((DOMAIN,static.zhihu.com))), (NOT,((DOMAIN,api.zhihu.com))), (NOT,((DOMAIN,link.zhihu.com))), (NOT,((DOMAIN,lens.zhihu.com))), (NOT,((DOMAIN,www.zhihu.com))), (NOT,((DOMAIN-SUFFIX,zhimg.com))))
AND,((USER-AGENT,ZhihuHybrid*), (NOT,((DOMAIN-SUFFIX,zhihu.com))), (NOT,((DOMAIN-SUFFIX,zhimg.com))))

误杀严重，会导致知乎中要打开外链打不开等问题

**Comment by Liquor030** [comment]
URL-REGEX,^https?:\/\/pic\d\.zhimg\.com\/v2.+
这条会误杀一些头像

**Comment by NobyDa** [comment]
知乎激进阻止规则因需配合脚本, 不可避免有误杀, 如影响体验请将以下规则添加直连:
AND,((USER-AGENT,osee2*), (NOT,((DOMAIN-SUFFIX,zhihu.com))), (NOT,((DOMAIN-SUFFIX,zhimg.com))))
