### ISSUE TITLE
AdRule误杀相关

### ISSUE THREAD

**Issue by Mon5ter777** [NobyDa/Script#94]
我使用surge时发现AdRuleTest.list中的appsupport.qq.com与cgi.connect.qq.com会导致无法从别的软件分享内容到QQ启用后会显示发生异常，无法分享，禁用规则后正常显示(但是safari无论禁用还是启用规则均能正常分享，查看最近请求后发现少了cgi.connect.qq.com，可能是这个原因)。
其次发现AdRuleRegex.list中的api.unipay.qq.com会导致QQ开通超级会员时候出现网络问题，无法唤起支付选项。

**Comment by NobyDa** [comment]
已删除.
