### ISSUE TITLE
哔哩哔哩 1080P

### ISSUE THREAD

**Issue by JEGNUI** [NobyDa/Script#95]
我的这个使用无效，是脚本失效了么？请问您那边使用正常么？

**Comment by q602839678** [comment]
正常



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: JEGNUI <notifications@github.com&gt;
发送时间: 2020年4月3日 09:10
收件人: NobyDa/Script <Script@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[NobyDa/Script] 哔哩哔哩 1080P (#95)





 
我的这个使用无效，是脚本失效了么？请问您那边使用正常么？
