### ISSUE TITLE
quanX: b站(iOS)误杀反馈

### ISSUE THREAD

**Issue by eMeab** [NobyDa/Script#99]
开启Rewrite会导致个人中心被隐藏， 请确认

![image](https://user-images.githubusercontent.com/32988354/78565862-0af90f00-7851-11ea-9654-3361a53e7803.png)

**Comment by eMeab** [comment]
`^https://app.bilibili.com/x/v2/account/mine\?access_key url script-response-body https://raw.githubusercontent.com/NobyDa/Script/master/QuantumultX/File/bilibiliAccount.js`
确认是这条规则的问题 去除后已修正

**Comment by NobyDa** [comment]
这个就是去掉个人中心的, 脚本名已经标明Account

**Comment by eMeab** [comment]
好吧，但我个人觉得去除后非常不方便 无法查看历史记录 我close了
